### ISSUE TITLE
Setup script tests

### ISSUE THREAD

**Issue by IvanGrginovInf** [infinum/eightshift-frontend-libs#11]
We need to setup unit, integration and ideally e2e tests for setup scripts. (Maybe e2e tests should go to https://github.com/infinum/eightshift-boilerplate repo?)

Some unit tests are complete however, they're working with travis currently.

So steps to close this issue are:

- [x] Fix current unit tests
- [x] Write tests for the rest of functionality
- [ ] Setup a travis file so tests are automatically run on each commit

**Comment by IvanGrginovInf** [comment]
Most of the work will be done after https://github.com/infinum/eightshift-frontend-libs/pull/49 if merged. The only thing that's left is to setup the tests to run every X hours (probably using github actions).

**Comment by dingo-d** [comment]
> The only thing that's left is to setup the tests to run every X hours (probably using github actions).

You meant for e2e tests to run every few hours?

**Comment by IvanGrginovInf** [comment]
> You meant for e2e tests to run every few hours?

Yes.

Ideally it would run on each PR open but due to the way setup script works, it would really challenging to make it run this way (We'd need some kind of way to say: "setup WP-Boilerplate but use arbitrary branch of `eigthshift-frontend-libs` instead of what it says in `package.lock`)

**Comment by iruzevic** [comment]
is this done? @IvanGrginovInf

**Comment by IvanGrginovInf** [comment]
> is this done? @IvanGrginovInf

See reply above, I still need to make the tests run automatically on a cron.

**Comment by IvanGrginovInf** [comment]
Found a better way then running tests periodically on a cron, see #71.

Closing issue since the tests are implemented, we can continue with automating tests discussion in the issue #71
