### ISSUE TITLE
[BUG] Heading toolbar numbers positioning 

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#114]
It seems that the toolbar component in heading component has some style clashes 

![Screenshot 2020-05-04 at 15 59 08](https://user-images.githubusercontent.com/8638515/80975917-0cebc900-8e23-11ea-8c61-a7ce628cea4e.png)

The numbers (`after` pseudoelement) is aligned to the right absolutely.

**Comment by iruzevic** [comment]
This is fixed
