### ISSUE TITLE
Rewrite scroll-to function

### ISSUE THREAD

**Issue by gabriel-glo** [infinum/eightshift-frontend-libs#13]
Current implementation is using jQuery. 
I'd like to clean it up to use window.scroll function with polyfill for IE11.
Sample:
https://codepen.io/gloga/pen/oNNZEvM

**Comment by kmaric69** [comment]
@gabriel-glo  jQuery has been removed from frontend libs, but it would be nice to do a check on the scroll-to function.
If everything is fine you can close it.

**Comment by gabriel-glo** [comment]
Scroll to top component was already present and now there is a PR for scroll to target component: https://github.com/infinum/eightshift-frontend-libs/pull/92 . Once that PR is merged this issue will be closed.
