### ISSUE TITLE
Explore how to update @infinumjs/eslint-config to version 2.0.0

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#147]
- it requires typescript and it fails because of that

**Comment by dingo-d** [comment]
Should we just fork it for `@eightshift/eslint-config` and modify the things we don't need?

**Comment by IvanGrginovInf** [comment]
Erm, we already seem to have it? https://www.npmjs.com/package/@eightshift/eslint-config

**Comment by dingo-d** [comment]
Why aren't we using it? 👀 

Btw, not sure if you are following it: https://github.com/infinum/js-linters/issues/26

JS team would like to create one for WP, so we can either help them or use our own 🙂

**Comment by iruzevic** [comment]
We were using it but it ended up breaking the linter all-together because it expects to have typescript so I have rolled back the version to 1.3.

**Comment by iruzevic** [comment]
done
