### ISSUE TITLE
[BUG] Eslint errors on template strings

### ISSUE THREAD

**Issue by IvanGrginovInf** [infinum/eightshift-frontend-libs#156]
On one of my projects I seemed to be getting ESLint errors when using template strings after upgrading frontend-libs to 3.3.0 and then subsequently to 3.4.0, for example this line (among others) was throwing errors:

```js
this.swiperWrapperElement.style.marginLeft = `-${translateX}px`;
```

The errors were initially:

```
Oops! Something went wrong! :(

ESLint: 7.1.0

TypeError: Cannot read property 'value' of null
Occurred while linting /Users/ivangrginov/local-by-flywheel/www-other/d66/app/public/wp-content/themes/d66/src/blocks/components/carousel-slider/assets/carousel-slider.js:66
```

And on previous version (3.3.0 I also saw):

```
Oops! Something went wrong! :(

ESLint: 7.1.0

TypeError: Cannot read property 'range' of null
Occurred while linting /Users/ivangrginov/local-by-flywheel/www-other/d66/app/public/wp-content/themes/d66/src/blocks/components/carousel-slider/assets/carousel-slider.js:1
```

## Workaround

I've managed to fix the issue by adding the following to `.eslintrc`:

```
    "template-curly-spacing": "off",
    "indent": ["error", 2, {
        "ignoredNodes": [
          "TemplateLiteral"
        ]
    }]
```

Credit: https://github.com/babel/babel-eslint/issues/799#issuecomment-568195009

I'm not sure if this happens on fresh installs, need to check.

**Comment by iruzevic** [comment]
fixed
