### ISSUE TITLE
Carousel Image missing during Boilerplate installation [BUG] 

### ISSUE THREAD

**Issue by kmaric69** [infinum/eightshift-frontend-libs#159]
## Describe the bug

I get and error while installing the Boilerplate using `npx create-wp-project`. The error says that it failed during building assets. I took a deeper look and noticed that the issue happens because the image block requires the Carousel Image component. The image block contains a file `transforms.js` which requires the component.

## Steps to Reproduce

1. Setup new WordPress installation
2. Run `npx create-wp-project`
3. Add name for project and URL

## Expected behavior

Should not fail during installation.

## Your Environment

* PHP version:
* Development environment: 
* Server type: 
* Operating System and version:

**Comment by IvanGrginovInf** [comment]
Fixed in the setup script by copying the carousel block and it's connected components (already published so we don't have boilerplate down during the weekend), see PR: #160
