### ISSUE TITLE
[BUG] Removing blocks from the theme throws error on webpack run

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#162]
In the theme, if you remove `src/blocks/manifest.json` you'll get an error when running `npm run start` about missing `manifest.json`.

It's because `const globalSettings = require(options.config.blocksManifestSettingsPath);` expects the manifest file. Instead it should just pass over missing file.

**Comment by iruzevic** [comment]
this is fixed
