### ISSUE TITLE
[FEATURE] Update .gitattributes with all the production unnecessary files

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#165]
We should see what files we need, vs don't need for release/production so that the package is kept reasonably small. 
For instance, when you are using it, you don't need its internal storybook (used for development). Or docs for every block. All these files are for internal use, and for the development.

**Comment by iruzevic** [comment]
Internal storybook I agree, But blocks docs are necessary because without that storybook will fail. We have added details on every block but notes are here for to add project specific notes for every block. So we should leave this

**Comment by dingo-d** [comment]
Even in production where you don't need storybook?

**Comment by iruzevic** [comment]
If you don't want storybook you can remove docs folder from every block. But by default you get project specific storybook and you can remove it if you want

**Comment by dingo-d** [comment]
But why remove it by hand when, in production env, you can just have specified those in `.gitattributes` and they'll never be pulled. When developing they would be included.

**Comment by iruzevic** [comment]
done
