### ISSUE TITLE
jumbo

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#175]
There is problem with z-index on jumbotrone. Cannot select image.

**Comment by IvanGrginovInf** [comment]
Hi @marijang, can you provide some more details? For example:

- Screenshot
- Are you using the default block or have you made any modifications to it?
- Which frontend-libs version are you using?
- Which WP version are you using?

**Comment by iruzevic** [comment]
We will update this in a next release 4.0.1 with. at new Jumbron setup
