### ISSUE TITLE
global setting

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#176]
if I put font colors in manifest

```json
 "fontcolors": [
      {
        "name": "Primary",
        "slug": "primary",
        "color": "#C3151B"
      },
      {
        "name": "Black",
        "slug": "black",
        "color": "#000000"
      },
    ],
```

and then use `color: global-settings(fontcolors,primary)`, --> not works

**Comment by IvanGrginovInf** [comment]
Hi @marijang, have you restarted watch process after adding the color? (`npm start`)

Manifests are cached while watch is running. If you make any changes to a manifest (either the global manifest or block's manifest), you need to cancel the existing watch process and start a new one (`npm start`).

**Comment by marijang** [comment]
> Hi @marijang, have you restarted watch process after adding the color? (`npm start`)
> 
> Manifests are cached while watch is running. If you make any changes to a manifest (either the global manifest or block's manifest), you need to cancel the existing watch process and start a new one (`npm start`).

I try that but i get error 

SassError: SassError: ERROR: Specified index does not exist in map (0: (name: Primary, slug: primary, fontcolor: #C3151B), 1: (name: Black, slug: black, color: #000000), 2: (name: White, slug: white, color: #FFFFFF)), with value: primary

**Comment by IvanGrginovInf** [comment]
@marijang Actually, `colors` key in manifest works a bit different, if you need to add colors you should just add them after the other colors in the `colors` key in manifest like so (or change the existing ones):

```json
  "colors": [
      {
        "name": "Primary",
        "slug": "primary",
        "color": "#C3151B"
      },
      {
        "name": "Black",
        "slug": "black",
        "color": "#000000"
      },
      {
        "name": "White",
        "slug": "white",
        "color": "#FFFFFF"
      },
      {
        "name": "Your custom color",
        "slug": "customColor",
        "color": "#ABABAB"
      }
  ]
```

If you really need a different key (such as `fontcolors`) you'll have to use the syntax for all other manifest items. **Note that this isn't really recommended as some things (such as the native color picker component) won't work with these colors and you should rather keep them all in the `colors` manifest key**. But you **_can_** do this for example.` (NOT RECOMMENDED):

```json
 "fontcolors": {
      "primary": "#C3151B",
      "black": "#000",
      "customColor": "#ABABAB"
  },
```

**Comment by marijang** [comment]
> @marijang Actually, `colors` key in manifest works a bit different, if you need to add colors you should just add them after the other colors in the `colors` key in manifest like so (or change the existing ones):
> 
> ```json
>   "colors": [
>       {
>         "name": "Primary",
>         "slug": "primary",
>         "color": "#C3151B"
>       },
>       {
>         "name": "Black",
>         "slug": "black",
>         "color": "#000000"
>       },
>       {
>         "name": "White",
>         "slug": "white",
>         "color": "#FFFFFF"
>       },
>       {
>         "name": "Your custom color",
>         "slug": "customColor",
>         "color": "#ABABAB"
>       }
>   ]
> ```
> 
> If you really need a different key (such as `fontcolors`) you'll have to use the syntax for all other manifest items. **Note that this isn't really recommended as some things (such as the native color picker component) won't work with these colors and you should rather keep them all in the `colors` manifest key**. But you **_can_** do this for example.` (NOT RECOMMENDED):
> 
> ```json
>  "fontcolors": {
>       "primary": "#C3151B",
>       "black": "#000",
>       "customColor": "#ABABAB"
>   },
> ```

Thanks

**Comment by IvanGrginovInf** [comment]
You're welcome!
