### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Lovor01** [infinum/eightshift-frontend-libs#179]
## Describe the bug
Hello, upon installation and theme activation, there is an error and theme does not work (yes, I did steps 1. and 2. in wp.config upon installing with npx create-wp-project)
Following error occurs: Fatal error: Uncaught DI\Definition\Exception\InvalidDefinition: Entry "Web_MMMM_8\Core\Config" cannot be resolved: the class doesn't exist Full definition: Object ( class = #UNKNOWN# Web_MMMM_8\Core\Config lazy = false )

## Environment

* PHP version: 7.4.10
* Development environment: Wamp.net
* Server type: Apache
* Operating System and version: Windows 10

**Comment by dingo-d** [comment]
Hi!

Can you see if you have a file called `compiledContainer.php` in your codebase? If so try to remove it, and try to trigger `composer -o dump-autoload`.

This is a dependency injection container notice saying that the class `Web_MMMM_8\Core\Config` doesn't exist.

**Comment by Lovor01** [comment]
I've did it as you requested, but the error persists.

**Comment by IvanGrginovInf** [comment]
Hi @Lovor01 , can you please confirm you actually have a file `wp-content/themes/YOURTHEMENAME/src/class-config.php` called `Config` with namespace `Web_MMMM_8\Core`?

If so please check the following file `wp-content/themes/YOURTHEMENAME/vendor/composer/autoload_classmap.php` and confirm that you have an entry for `Web_MMMM_8\Core\Config` with the correct folder path.
