### ISSUE TITLE
Parameter #3 $icon of function wp_get_attachment_image expects bool string given

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#180]
In this component, phpstan gives the above error on line 29:

https://github.com/infinum/eightshift-frontend-libs/blob/52870b9bb5302e5723e68268aee3ba8849ed0c7a/blocks/init/src/blocks/components/image/image.php#L26-L31

Should be either `true` or `false`, not `''`.

**Comment by iruzevic** [comment]
This is removed fully
