### ISSUE TITLE
[FEATURE] Improve the button component

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#181]
Currently, the 'button' component is always a link (`a`). We should make a distinction whether we want this to be a link (URL provided) or just a button component that can be used in forms etc. (HTML `<button>` tag).

Besides that, if used as a link, new options should be added:

- `target` attribute with preset values in a dropdown
  - `_blank`, `_self`, `_parent`, `_top`
- `noreferrer` and `noopener` toggle (like in the core)
  - this should be researched a bit as it could have a SEO impact (https://twitter.com/jdevalk/status/1322300284748681216?s=20)

**Comment by goranalkovic-infinum** [comment]
`<a>` / '<button>` switching is already there, added improved link picker.
