### ISSUE TITLE
Hook 

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#183]
Hey, what you suggest if I need to pass options to child block?
Use hook or?

Do you have example for that?

**Comment by IvanGrginovInf** [comment]
If you need this in PHP you can use https://developer.wordpress.org/reference/hooks/render_block_data/ to override blocks attributes (or attributes of it's child blocks).

If you need to do this in JS, you're going to have to use `useSelect` (https://developer.wordpress.org/block-editor/packages/packages-data/#useSelect), get current block by `clientId` and then for all `innerBlocks` you can override their attributes.
