### ISSUE TITLE
[BUG] Project setup not working if you have and folder that has space in the path

### ISSUE THREAD

**Issue by iobrado** [infinum/eightshift-frontend-libs#184]
When I run npx create-wp-project from the folder that has space inside it like "Local Sites" git clone throws and error.

git clone fatal: Too many arguments.

**Comment by dingo-d** [comment]
That's a cool edge case. But please, don't use spaces in folder names 😂  They will haunt you if you'll have to use a terminal 😄

**Comment by iobrado** [comment]
That was by default from WP-Local. Gotta see if that can be changed 😄

**Comment by IvanGrginovInf** [comment]
Fixed in `create-wp-project@2.0.7`
