### ISSUE TITLE
[BUG] Column inner blocks

### ISSUE THREAD

**Issue by JerrySpecter** [infinum/eightshift-frontend-libs#195]
Hi,

I'm using release 4 of `eightshift-frontend-libs`.

I was expecting to have spacing sliders but, any inner block of column block only has limited options in the `Block layout` panel.

Example:

1. Add `Columns` block
2. Add `Column` block
3. Add `Heading` block
4. When selected, heading block does not have spacing options in `Block layout` panel.

![image](https://user-images.githubusercontent.com/25869062/101391512-b5d03a00-38c4-11eb-8cc2-b04648eafa7a.png)

Is this intended or are there some options that need to be added? 

When I add only the `Heading` block then all options are available.

**Comment by iruzevic** [comment]
Have you tried scrolling to the bottom? Heading options should be at the bottom of the options.

![Uploading Screenshot 2020-12-07 at 19.52.24.png…]()

**Comment by JerrySpecter** [comment]
I was talking about wrapper options of Heading block.

Standalone heading block (green color heading):
- has spacing options in Block layout panel

![image](https://user-images.githubusercontent.com/25869062/101392777-71459e00-38c6-11eb-93c6-c73e4d8ea942.png)

Heading inside of a column block (yellow background):
- does not have spacing options in Block layout panel

![image](https://user-images.githubusercontent.com/25869062/101393216-05176a00-38c7-11eb-8786-9b0580fd174b.png)

**Comment by gabriel-glo** [comment]
I have also tested this with the new installation and it looks like all inner blocks of Column block have Wrapper Simple Enabled toggle set to true while the standalone blocks have it set to false.

**Comment by IvanGrginovInf** [comment]
Yes all inner blocks should have `wrapperUseSimple` enabled (meaning you can only set top / bottom paddings and responsive block visibility and some other things on the inner blocks and all other wrapper settings only on the parent block). Tho it does seem that top / bottom padding is missing. I'll take a look at this. Also cc @iruzevic

**Comment by gabriel-glo** [comment]
I figured that we don't need full wrapper options like container size etc., but spacing top and bottom should be essential to this. Only weird thing is that I didn't find where this is assigned anywhere in the code. Is this set in libs?

**Comment by gabriel-glo** [comment]
I think I figured out the solution. Simple wrapper options were incorrectly defined.
With `wrapperUseSimple` set to `true` only options available were `wrapperWidth, `wrapperOffset`, `wrapperContainerWidth` and `wrapperGutter`, which did nothing since they require container elements to work.

`wrapperUseSimple` conditional in `wrapper-options.js` needs to be changed to allow `wrapperSpacingBottom` and `wrapperSpacingTop` to be usable.

**Comment by iruzevic** [comment]
Could you try to setup a new theme and see if it is fixed?

**Comment by gabriel-glo** [comment]
Did a new setup and now it works. This issue can be closed
