### ISSUE TITLE
[BUG] Icons missing in the wrapper

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#200]
![Screenshot 2020-12-14 at 15 37 24](https://user-images.githubusercontent.com/8638515/102094353-82d8f980-3e22-11eb-9bf6-7d6ee2ea116c.png)

Seems like the icons are not showing 🤷🏼‍♂️

**Comment by IvanGrginovInf** [comment]
Which version of WP do you have on the site? @dingo-d

**Comment by iruzevic** [comment]
This is an issue with the latest WP version but not with the that versions libs for some reason. I will need to investigate on this

**Comment by dingo-d** [comment]
> Which version of WP do you have on the site? @dingo-d

WP 5.6
