### ISSUE TITLE
How to use useSelect

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#205]
Hey,

i want to get all post categories in options?
So i put in options for example

```js
const categories = useSelect(select =>
     select('core').getEntityRecords('taxonomy', 'category')
);

<SelectControl
          label={__('Post Type', 'b4b')}
          value={categoryId}
          options={categories.map(({id, name}) => ({label: name, value: id}))}
          onChange={onChangeCategory}
/>
```

and then in block.js

```js
useSelect( ( select ) => {
    let query = {
      categories: [categoryId],
      order: 'asc',
    };
    return {posts: select('core').getEntityRecords('postType', 'post', query)}
  } );
```

Not working and i see that use select fire multiple times???
Also it is not good category_id...

**Comment by marijang** [comment]
My block

`import React, { useState } from 'react'; // eslint-disable-line no-unused-vars
import { InspectorControls } from '@wordpress/block-editor';
import { Fragment } from '@wordpress/element';
import { Spinner } from '@wordpress/components';
import { __ } from '@wordpress/i18n';
import { getActions } from '@eightshift/frontend-libs/scripts/editor';
import apiFetch from '@wordpress/api-fetch'; // eslint-disable-line import/no-extraneous-dependencies
import manifest from './manifest.json';
import { FeaturedProjectsEditor } from './components/featured-projects-editor';
import { FeaturedProjectsOptions } from './components/featured-projects-options';
import { useSelect,withSelect } from '@wordpress/data';


export const B4bBlogCategory = (props) => {

  //console.log(props);
  const {
    setAttributes,
    attributes,
    attributes: {
      postType,
      posts,
      category,
      postList
    },
    
  } = props;

  const [postCategories, setPostCategories] = useState(1);
  const [postResults, setPostResults] = useState(posts);
  
  const query = {
    categories: [category],
    order: 'asc',
  };
  
  const newPosts = useSelect( ( select ) => {
    return select('core').getEntityRecords('postType', 'post', query)
  }, [ category,query,posts ] );


  useSelect((select) => {
    return {
      posts: select('core').getEntityRecords('postType', 'post', query)
    }
  },[posts,query]);


  const actions = {
    ...getActions(props, manifest),
    onChangeCategory: (value) => {
      setAttributes({
        category: value,
      });
    },
  };


  return (
    <Fragment>
      <InspectorControls>
        <FeaturedProjectsOptions
          attributes={{ ...attributes, postResults }}
          actions={actions}
        />
      </InspectorControls>
      
      {!posts.length ?
        <Fragment>
          {__('Click to select posts', 'eightshift-boilerplate')}
          <Spinner />
        </Fragment> :
        <FeaturedProjectsEditor
          attributes={attributes}
          actions={actions}
        />
      }
    </Fragment>
  );
};
`






My options file

`import React, { useState } from 'react'; // eslint-disable-line no-unused-vars
import { __ } from '@wordpress/i18n';
import {useSelect,select} from '@wordpress/data';
import { PanelBody, SelectControl, FormTokenField, RangeControl } from '@wordpress/components';

export const BlogOptions = ({ attributes, actions }) => {
  const {
    postNames,
    postNumber,
    postType,
    postResults,
    category,
    postOffsetNumber
  } = attributes;

  const {
    onChangePostType,
    onChangePostNumber,
    onChangePostOffsetNumber,
    onChangeCategory,
    onChangePostInput,
    onChangePost,

  } = actions;

  let suggestions = [];


useSelect((select) => {
    const categories =  select('core').getEntityRecords('taxonomy', 'category');
});







  return (
    <PanelBody title={__('Blog category', 'eightshift-boilerplate')}>


    {onChangePostOffsetNumber &&
        <RangeControl
          value={postOffsetNumber}
          allowReset={true}
          label={__('Number offset of posts', 'b4b')}
          onChange={onChangePostOffsetNumber}
          min={1}
          max={100}
        />
      }

      {onChangePostNumber &&
        <RangeControl
          value={postNumber}
          allowReset={true}
          label={__('Number of posts to show', 'b4b')}
          onChange={onChangePostNumber}
          min={1}
          max={100}
        />
      }
      
      {categories &&
        <SelectControl
          label={__('Post Type', 'b4b')}
          value={category}
          options={categories.map(({id, name}) => ({label: name, value: id}))}
          onChange={onChangeCategory}
        />
        
      }

      {onChangePostInput &&
        <FormTokenField
          value={postNames}
          suggestions={suggestions}
          onInputChange={onChangePostInput}
          onChange={onChangePost}
          maxLength={postNumber}
          label={__('Select posts', 'eightshift-boilerplate')}
        />
      }
    </PanelBody>
  );
};
`

**Comment by IvanGrginovInf** [comment]
Hi @marijang, the following code works for me:

```js
  const categories = useSelect((select) => {
    return select('core').getEntityRecords('taxonomy', 'category');
  });

  const posts = useSelect((select) => {

    // Don't do anything if previous category hook didn't yet finish.
    if (!categories || categories.length === 0) {
      return [];
    }

    const query = {
      categories: [categories[0].id],
      order: 'asc',
    };
    return { posts: select('core').getEntityRecords('postType', 'post', query) };
  }) || [];

  console.log('posts', posts);
```

> Not working and i see that use select fire multiple times???

Yes it fires on every re-render, same as with all other React code in the options / editor (React rerenders on every change to state / props).  You need to guard against rerenders before hook has finished fetching the data (i.e. the renders where your `categories` & `posts` variables are still empty) which is what the following like does:

```js
    // Don't do anything if previous category hook didn't yet finish.
    if (!categories || categories.length === 0) {
      return [];
    }
```

Also notice the ` }) || [];` at the end of the `useSelect` which fetches posts. This is just a simple way to ensure you always get an array (and not `null`) in `posts` before `select` has done it's thing but it's not necessary if you guard against it.

Hope this helps.

**Comment by marijang** [comment]
Posts is readonly....:D

**Comment by marijang** [comment]
From manifest variable.

Scenario is

Options
1. User choose blog category
2. User pick number of posts
3. User pick offset number

-Block.js onChangeCategory => refresh posts

**Comment by marijang** [comment]
`  if (!newPosts || newPosts.length !== 0) {
    setAttributes({
      posts: newPosts,
    });
  }`

end up with

**Comment by iruzevic** [comment]
You can check this 3 blocks for more details on how to use useSelect

https://github.com/infinum/eightshift-frontend-libs/tree/release/4.0.0/blocks/init/src/Blocks/custom

- featured-categories-posts
- featured-categories
- featured-posts

**Comment by marijang** [comment]
is it save to run update?

**Comment by iruzevic** [comment]
Yes you can update the frontend-libs(package.json) and libs(composer.json). We didn't do any major breaking changes.  But I can't guarantee

**Comment by dingo-d** [comment]
> We didn't do any major breaking changes

Famous last words 😅  😂

**Comment by marijang** [comment]
Last time was show:D

**Comment by marijang** [comment]
Great work

**Comment by marijang** [comment]
what is lates  version to update?

i put     "@eightshift/frontend-libs": "^4.0.0", not working

**Comment by dingo-d** [comment]
It should be (if I'm not mistaken)

```
"@eightshift/frontend-libs": "git+https://github.com/infinum/eightshift-frontend-libs.git#release/4.0.0"
```

**Comment by marijang** [comment]
put inside update instructions:
"add light color " inside manifest

**Comment by marijang** [comment]
and composer?

**Comment by iruzevic** [comment]
Please check the github.com eightshift-boilerplate there is everything set in composer and in package

**Comment by marijang** [comment]
> We didn't do any major breaking changes

Hahhahah yep right.....:)
