### ISSUE TITLE
[BUG] wp.blockEditor.RichText formattingControls prop is deprecated. Please use allowedFormats instead.

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#214]
Got the above notice while working on the component in the Storybook. We are using `formattingControls` in several places in our components.

https://github.com/infinum/eightshift-frontend-libs/search?q=formattingControls

**Comment by iruzevic** [comment]
I tried to changed it too what it sayed and it wasn't working :(  I will try in the next code relase

**Comment by dingo-d** [comment]
When replacing the `formattingControls` with `allowedFormats` the passed options must be namespaced. So instead of this

```js
<RichText
	className={paragraphClass}
	placeholder={placeholder}
	value={paragraphContent}
	onChange={(value) => setAttributes({ [`${componentName}Content`]: value })}
	formattingControls={['bold', 'link']}
/>```

you'd have to change it to

```js
<RichText
	className={paragraphClass}
	placeholder={placeholder}
	value={paragraphContent}
	onChange={(value) => setAttributes({ [`${componentName}Content`]: value })}
	allowedFormats={['core/bold', 'core/link']}
/>
```

**Comment by iruzevic** [comment]
aha okej i will test it tnx. Well if I had some kind of documentation from the WP core #hint #hint

**Comment by iruzevic** [comment]
Yep this works
