### ISSUE TITLE
[BUG] Possible issue when using onChange with components that have compound words

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#222]
I noticed in a project where we have `jumbotron-cta` component inside the `ToggleControl` the 

 ```js
<ToggleControl
	label={sprintf(__('Use %s', 'immunicom'), label)}
	checked={jumbotronCtaUse}
	onChange={(value) => setAttributes({ [`${componentName}Use`]: value })}
```

won't work, because the `componentName` is `jumbotron-cta`. So to circumvent this a colleague added a function called `camelize` that will turn that to camel case `jumbotronCta`.

Now, one option is to just avoid using dashes as component names, and make sure that the component names are always camel-cased, or to add this as a helper to use.

Which one do you think is a better approach?

I lean on enforcing that the name must be camel-cased in the manifest. That way we don't have to worry about any edge cases, using underscores, semicolons, etc.

**Comment by iruzevic** [comment]
Personally I don't see any issues on adding this helper in the libs. Regarding the components name I'm gravitating a little bit towards using the camelcase for names.

what do you guys think?

**Comment by dingo-d** [comment]
@infinum/wordpress-team thoughts?

**Comment by IvanGrginovInf** [comment]
Isn't `componentName` ultimately used for class names? Meaning we'd have camel case classes which I'm not a fan of `class="jumbotronCta__element"`

**Comment by gabriel-glo** [comment]
`componentClass` is used for class names. Component name could be written in camel case, because that's not being shown anywhere on the front or in editor.

**Comment by dingo-d** [comment]
I think @JerrySpecter tried using camel case and there was some import issue. Can you explain some more?

**Comment by iruzevic** [comment]
We added the camelize helper and I have created an issue on docs to explain this https://github.com/infinum/eightshift-docs/issues/72
