### ISSUE TITLE
Check how we can make Yoast Seo scrape our content in attributes

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#231]
https://developer.yoast.com/customization/yoast-seo/adding-custom-data-analysis/

https://wordpress.org/support/topic/how-is-the-readability-and-seo-score-generated/

**Comment by dingo-d** [comment]
I think this is kinda related to the same issue. The info icon doesn't pick up on the content in the attributes, so everything is reported as 0 (except blocks)

![Screenshot 2021-01-29 at 10 52 01](https://user-images.githubusercontent.com/8638515/106259926-22f6b080-6220-11eb-8a94-c7f3c0452a95.png)

**Comment by iruzevic** [comment]
This issue is addressed in a new ticket:
https://github.com/infinum/eightshift-frontend-libs/issues/250

**Comment by iruzevic** [comment]
I have made this update in the pr but there is only option to add additional content to the analyser.

Currently there is not way to specify internal and ounbount links and also alt tags for images. 

https://github.com/Yoast/javascript/blob/a60160390eefdf639e98b17a06eb028631c1c7c3/packages/yoastseo/docs/Customization.md#modifications

I will open an issue on YoastSeo

![Screenshot 2021-02-01 at 08 33 17](https://user-images.githubusercontent.com/23283324/106427732-27ada580-6468-11eb-9534-80277b1d1ce9.png)

**Comment by mbmjertan** [comment]
Bringing this up: could we (should we?) wrap images in an HTML tag here? As Yoast does content analysis on HTML, that could work? We're currently just concatenating attributes that have `seo: true` to Yoast's data.

https://github.com/infinum/eightshift-frontend-libs/blob/0ffff6c9c086c1a490bcf36804baeaddeff4f1f3/scripts/plugins/yoast-seo.js#L39-L66
