### ISSUE TITLE
Flex in image wrap distorts the image when used in other components

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#233]
https://github.com/infinum/eightshift-frontend-libs/blob/59c6fa2a1a00786d0078ae0b673c68b69e84485c/blocks/init/src/Blocks/components/image/image-style.scss#L16-L20

I've noticed when the image component is being used in other components or blocks (image-text block for instance) in a flex container, this will cause the image to expand and proportions will look distorted.

It's because of the `flex` in the wrapper. Well, technically, it's due to the fact that there is a flex container around it.

So either this needs to be removed, or any containing elements shouldn't be `flex` (`grid` maybe?).

**Comment by iruzevic** [comment]
Not sure what do you mean can you provide a code example. I have tried to recreate by putting display flex on the outer container and it looks ok
<img width="1710" alt="Screenshot 2021-01-15 at 23 46 32" src="https://user-images.githubusercontent.com/23283324/104785948-0c664900-578c-11eb-8752-67c408af3643.png">
