### ISSUE TITLE
[BUG] If project name has multiple words, boilerplate setup adds underscore in namespace

### ISSUE THREAD

**Issue by iobrado** [infinum/eightshift-frontend-libs#235]
When creating new project with `npx create-wp-project`, if multiple words are used in Project Name, e.g. New Project, auto-generated namespace will be New_Project instead of NewProject.

Screenshot below:
![Screenshot 2021-01-15 at 15 07 07](https://user-images.githubusercontent.com/23059501/104736529-668eec00-5743-11eb-838b-039d5126ca95.png)

**Comment by IvanGrginovInf** [comment]
> Could be related to #234

Yes, can be done as a single fix, thanks for connecting them. Yup, this needs to be changed after we changed cases on the project in the new boilerplate.

**Comment by iruzevic** [comment]
@IvanGrginovInf was this fixed in the latest fix?

**Comment by IvanGrginovInf** [comment]
@iruzevic no forgot all about this one, will fix it today. 🙈
