### ISSUE TITLE
[BUG] Build process generates .php files alongside the bundled js files

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#238]
Not sure which package does this, but I'm not sure why it does this and I don't think that we are using any of those. 

They are problematic because the builds keep failing on the composer linting.

**Comment by iruzevic** [comment]
not sure what you are referring to

**Comment by dingo-d** [comment]
![Screenshot 2021-01-18 at 12 29 25](https://user-images.githubusercontent.com/8638515/104909880-d17d3480-5988-11eb-8992-94f41be850d5.png)

When I run `npm run build` on a clean install I get the above image (notice all the .php files in the `public` folder).
