### ISSUE TITLE
[FEATURE] Add automatic select to featured posts selection

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#243]
In the featured posts block, we have the option to select which posts we want to show. Which is ok if we have 10 posts. But, when we go to the 30-100 range, if the client wants to select some posts, that could prove difficult (not to mention that there is a limitation on REST API to display at max 100 posts IIRC).

A better alternative is to have a sort of select2 post field that you can select from dynamically - start typing and autosuggestion would pop up with posts.

This is better for performance plus it's more user friendly.

**Comment by dingo-d** [comment]
I think this was already added in #279 with the custom select @iruzevic ? If I'm correct feel free to close this one.

**Comment by goranalkovic-infinum** [comment]
@dingo-d 
We're using CustomSelect now for the picker, but still the WP useSelect. If we included apiFetch, we could do a searchable async CustomSelect.

**Comment by iruzevic** [comment]
duplicate
