### ISSUE TITLE
Write descriptions and make images for wrapper and column helpers modal

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#244]
<img width="1020" alt="Screenshot 2021-01-26 at 17 44 08" src="https://user-images.githubusercontent.com/23283324/105875472-201c7580-5ffe-11eb-8fb8-d127a191523f.png">

**Comment by goranalkovic-infinum** [comment]
Here's a proposition of the new descriptions and visual describing various _Columns_ and _Wrapper_ features:

![image](https://user-images.githubusercontent.com/77000136/106284700-d2914a00-6243-11eb-9605-34d1ead33d52.png)

These could be displayed in rows (like in the current implementation) or shown as card that would wrap.

**Comment by dingo-d** [comment]
This looks awesome 😍

**Comment by iruzevic** [comment]
This looks sooo good

**Comment by goranalkovic-infinum** [comment]
Glad you like it!

What do you think about renaming `spacingTopIn` and `spacingBottomIn` to `paddingTop` and `paddingBottom`? The code-behind name could stay the same for now not to break anything.

**Comment by iruzevic** [comment]
I would leave it like this. This us used by content editors and they don't know what margin and padding is

**Comment by goranalkovic-infinum** [comment]
Is this ready to be implemented (without changing the `spacingXIn` names)? Are all the proposed descriptions ok?

**Comment by iruzevic** [comment]
yep looks good
