### ISSUE TITLE
Fix custom icons for wrapper, column, and columns

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#245]
Make icons that represents the action

**Comment by goranalkovic-infinum** [comment]
Some icons have multiple suggested variations.

Existing icons:
![image](https://user-images.githubusercontent.com/77000136/106273007-3c085d00-6232-11eb-9a1a-f329e6967d5b.png)

New icons:
![image](https://user-images.githubusercontent.com/77000136/106273025-432f6b00-6232-11eb-8f69-a23753a3c9bb.png)

**Comment by goranalkovic-infinum** [comment]
Here's a preview in the editor:
![image](https://user-images.githubusercontent.com/77000136/106273533-22b3e080-6233-11eb-80d5-e389f2ca4549.png)

**Comment by dingo-d** [comment]
Noice! 😄

**Comment by iruzevic** [comment]
Soo awesome, I know we are not using container spacing in libs but it can be used in projects so make a icon for this and you are missing and icon go spacing top in and spacing bottom in

**Comment by goranalkovic-infinum** [comment]
Here's a `containerSpacing` icon:
![image](https://user-images.githubusercontent.com/77000136/106440369-14570600-6479-11eb-9751-b001634cf59b.png)

(not sure if it should be something like margin or padding)

New icons:
![image](https://user-images.githubusercontent.com/77000136/106440619-56804780-6479-11eb-909d-f780ca319e69.png)

**Comment by goranalkovic-infinum** [comment]
Are these ready to be integrated?

**Comment by iruzevic** [comment]
yap

**Comment by dingo-d** [comment]
@goranalkovic-infinum can you create an icon for rounded corners as well? 🙏🏼  👀
