### ISSUE TITLE
Missing block icons

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#264]
* Email
* Shortcode
* FeaturedCategoriesPosts

Also can you make few card variations like 5-6 so we can use them on different projects

**Comment by goranalkovic-infinum** [comment]
Anything specific to be on the cards (for example img/text combo, lists, etc) or just 5-6 random cards?

**Comment by iruzevic** [comment]
It really doesn't mater like 5-6 random cards so we can use them

**Comment by dingo-d** [comment]
I've added these

![Screenshot 2021-02-03 at 16 51 20](https://user-images.githubusercontent.com/8638515/106772252-1cad6d80-6640-11eb-82fc-bc20472a3623.png)

**Comment by goranalkovic-infinum** [comment]
@dingo-d a couple of regards, now that I see the icons in bigger size:
- Please make sure that arrows and similar shapes have rounded edges.
- Font for numbers etc should be _Open Sans_.
- Border radius on most things should be 1.5

**Comment by dingo-d** [comment]
Feel free to make the changes, I just copied over stuff from the other icons and patched together new ones 😂

**Comment by goranalkovic-infinum** [comment]
Haha deal!

**Comment by goranalkovic-infinum** [comment]
New icons for today, and some that @dingo-d made but made to fit in a bit more with the rest.

![image](https://user-images.githubusercontent.com/77000136/107258911-a85a3c00-6a3c-11eb-9707-b94ba4c48481.png)
