### ISSUE TITLE
[BUG] Icons foreground not working 

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#265]
Icons foreground color not working as in picker does. They are black in some cases

https://user-images.githubusercontent.com/23283324/106748652-d5b27e80-6625-11eb-9e49-39765889dd25.mov

**Comment by dingo-d** [comment]
This is the default behavior. At least this was the case so far. Even when using dashicons 🤷🏼‍♂️

**Comment by goranalkovic-infinum** [comment]
It should pull the colors from the `Blocks/Manifest`, not sure why it's doing that.

More weird is that the backplate of the icon (the red part here) looks kinda warped and too narrow.

Guess we could override it in Editor styles, but as @dingo-d says, might be a Gutenberg bug.

**Comment by iruzevic** [comment]
Heading icon is working the rest are not. Im not sure that this is a core bug maybe it is ours could you please investigate

**Comment by goranalkovic-infinum** [comment]
Sure!

**Comment by goranalkovic-infinum** [comment]
Found the culprit (at least I think) - the icon is black when the button is disabled (aka when you can't convert the block to anything else), but the background stays whatever color is defined in the manifest.

**Comment by dingo-d** [comment]
Also, there is this: https://core.trac.wordpress.org/ticket/26350#comment:37

**Comment by goranalkovic-infinum** [comment]
What do you think about moving the icon colors from the manifest to our SCSS, there we can override the default colors.

Another option would be for the project setup to assign 2 SCSS variables with colors from manifest so they can be used in override-editor styles if needed.

**Comment by iruzevic** [comment]
> What do you think about moving the icon colors from the manifest to SCSS color definitions?
> 
> Another option would be for the project setup to assign 2 SCSS variables with colors from manifest so they can be used in override-editor styles if needed.

No this will be removing the native functionality. We must use as much as core functionality as possible.

**Comment by goranalkovic-infinum** [comment]
In that case only thing we can do at the moment is remove the color background if the button is disabled, just so it doesn't look weird.

**Comment by goranalkovic-infinum** [comment]
A couple of fixes

![image](https://user-images.githubusercontent.com/77000136/107661663-c5377f00-6c89-11eb-9bc1-e98f414653fb.png)

and an idea: 25% bigger eightshift icons (all the other ones stay the same)
![image](https://user-images.githubusercontent.com/77000136/107661753-dbddd600-6c89-11eb-9d73-ae5d9a6d8277.png)
