### ISSUE TITLE
Background paragraph and heading

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#277]
<img width="1543" alt="Screenshot 2021-02-09 at 17 34 21" src="https://user-images.githubusercontent.com/1381443/107395625-47df0380-6afd-11eb-9429-ee85ebe00242.png">

Why i can t change heading and paragraph color.
Also would be nice to change column background.

Blocks used:
 - group -> heading, paragraph

Thanks

**Comment by marijang** [comment]
also how to disable all other blocks in gutenberg?

**Comment by dingo-d** [comment]
You can read how to disable other blocks here: https://infinum.github.io/eightshift-docs/docs/basics/blocks-special-use-cases#how-to-only-use-my-custom-blocks

As for the background, it looks like some of the blocks have set bg color on them. When you inspect it, can you pinpoint where the white background is coming from?

**Comment by marijang** [comment]
https://user-images.githubusercontent.com/1381443/107499691-8f18d300-6b95-11eb-9f7b-7f8f5ea976b0.mov

<img width="736" alt="Screenshot 2021-02-10 at 11 43 42" src="https://user-images.githubusercontent.com/1381443/107499712-95a74a80-6b95-11eb-818c-66d07cf2bba5.png">

**Comment by dingo-d** [comment]
Every block has a wrapper on it. For you, the default bg color of the wrapper is probably set to white. Try adding transparent color to the wrapper and in the manifest set it as a default.

So in your `wrapper/manifest.json` in the `attributes` key set 

```json
		"wrapperBackgroundColor": {
			"type": "string",
			"default": "transparent"
		},
```

And also add it in the `colors` key. And ofc, make sure you have transparent defined in your main `manifest.json`, like

```json
"colors": [
			{
				"name": "Primary",
				"slug": "primary",
				"color": "#C3151B"
			},
			{
				"name": "Black",
				"slug": "black",
				"color": "#000000"
			},
			{
				"name": "Light",
				"slug": "light",
				"color": "#CCCCCC"
			},
			{
				"name": "White",
				"slug": "white",
				"color": "#FFFFFF"
			},
			{
				"name": "Transparent",
				"slug": "transparent",
				"color": "transparent"
			}
		]
```

**Comment by marijang** [comment]
hm...it will be great that block inside can change bg color.
for example 

i have 2 columns and i want to add to the right column grey background....
now i can't do that without creating a new custom block.

**Comment by dingo-d** [comment]
You could add a background color option to column block. Inside the `src/Blockls/custom/column/manifest.json` add something like

```json
	"options": {
		"breakpoints": [
			"large",
			"desktop",
			"tablet",
			"mobile"
		],
		"widths": {
			"min":  1,
			"max":  12,
			"step": 1
		},
		"offsets": {
			"min": 0,
			"max": 12,
			"step": 1
		},
		"orders": {
			"min":  1,
			"max":  20,
			"step": 1
		},
		"background-color": [
			"white",
			"black",
			"transparent"
		]
	}
```

Then in the `column-options.js` component you'd add before the `return`

```js
	const {
		backgroundColor,
	} = attributes;
```

And then in the component add something like

```js
<ColorPaletteCustom
	label={
		<Fragment>
			<Icon icon={icons.color} />
			{__('Column background color', 'eightshift-frontend-libs')}

		</Fragment>
	}
	value={backgroundColor}
	colors={getOptionColors(options.colors)}
	onChange={(value) => setAttributes({ backgroundColor: value })}
/>
```

This will give you a background color option on the column. Then all you'd need to add is some styling

```scss

$column: (
	background-color: (
		black: global-settings(colors, black),
		white: global-settings(colors, white),
		transparent: global-settings(colors, transparent),
	),
);

.block-column {
	@include column;

	position: relative;

	&__bg-color {
		@include modifiers-deep($column, background-color, background-color);
	}
}
```

Should work.

Now for the individual items in the inner blocks, not sure if that will work, at least not in an easy way. Because inner blocks usually have their wrapper disabled. They only have simple wrappers enabled so as not to add additional wrappers inside wrappers.

But, again, you can modify that behavior as well in your setup. Something with `"wrapperDisable": false,` settings if I'm not mistaken.

Hope this helps.

**Comment by marijang** [comment]
Danke
