### ISSUE TITLE
[FEATURE] Load more

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#285]
Hey how to make load more component for example for listing blog posts?
Also are you planing to support woocommerce?

Thanks.

**Comment by iruzevic** [comment]
You make a load more component that is universal and it can take query depending on the parent component. 

I'm making a load more component not and it should be up on a PR later this week.


Regarding the WooCommerce can you please provide more details what exactly should we check here regarding the WC support?

**Comment by marijang** [comment]
For woocommerce i think it is ok to start with command create_woo_support for wp boilerplate command 
- create wooMain class for overiding hooks
- create dir for styles
- would be nice to separate woocommerce components and blocks

Also i have question about comments 
where is best way to put/create WALKER class for comments (wp_list_comments('walker....')

Also would be nice to have breadcrumb component...

**Comment by iruzevic** [comment]
duplicate
