### ISSUE TITLE
[BUG] Remove all wp_kses_post from Components::render calls

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#286]
Currently, all our views get escaped on render. That is, wherever we have `echo` we do

```php
echo \wp_kses_post(Components::render('image', array_merge(
		$attributes,
		[
			'blockClass' => $componentClass
		]
	)));
```

because PHPCS will scream at us that we didn't escape our output. Technically this is true (echos should be escaped), but that doesn't mean that `Components::render` is unsafe. All components inside will escape attributes and content with the appropriate filters. Therefore making it safe down the line (late escaping).

The problem with eager escaping, besides making extra unnecessary function calls, is that you can have a compound component (component with multiple smaller 'dumb' components), and by escaping it early we risk removing certain attributes that make the component functional. Which will break the component.

So steps that we need to do in order to make this happen is:

1. Check that all our dumb components have properly escaped output - for instance SVGs need to be separately filtered, URLs in `href` attributes need to be escaped using `esc_url`, HTML should be filtered using `esc_html/wp_kses_post`, etc.
2. Remove all the `wp_kses_post` from `echo \wp_kses_post(Components::render());` constructs
3. Create rule for PHPCS to ignore errors coming from `Components::render()` calls
4. **Thoroughly test for security**. Pass all kinds of evil stuff in attributes and see if it will be rendered or escaped.

The last one is crucial.

**Comment by goranalkovic-infinum** [comment]
@dingo-d correct me if I'm wrong, but this could be closed now as recent PR to frontend libs removed unnecessary escapes and updates to the coding standards will prevent PHPCS from screaming at us?

**Comment by dingo-d** [comment]
Yeah, I still need to release and tag the new CS, and if **all** the escaping has been removed then this issue can be closed

**Comment by iruzevic** [comment]
this was removed
