### ISSUE TITLE
render blocking..

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#287]
Hey i create site with your theme and it is great....
so thanks maybe i can help you with some components:D

Also now I have gtm matrix report with this....
Resources are blocking the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles.

I use 
autooptimize and wpTotalCache

how to fix that

**Comment by dingo-d** [comment]
We use wp rocket on our sites, and never really had this issue.

Which scripts are reported as render blocking?

**Comment by marijang** [comment]
https://dementiewijzerdelft.onlyoneif.com/

Only one:D

hm wp rocket is it worth of buying?

**Comment by marijang** [comment]
Do you use cdn?

**Comment by dingo-d** [comment]
> hm wp rocket is it worth of buying?

Definitely. It's a super-powerful caching plugin that works like a charm. Also has tons of options for preloading and such.

The render-blocking resources are coming from google fonts being called as a script (which we never usually do), autooptimize minifying the CSS (try to see if there is a preload option for that), and jquery min being loaded (which we almost never use in our libs).

Also, one of your images is 1.3MB, you should really scale it down a bit and run it through https://tinypng.com/ to get a smaller size image. Anything above 300KB is considered heavy for the website.

> Do you use cdn?

So far never had the use for one.

**Comment by marijang** [comment]
how to remove jquery?

**Comment by dingo-d** [comment]
That depends on how are you enqueuing it, or if you have a plugin that uses it 🤷🏼‍♂️

**Comment by dingo-d** [comment]
I hope the above answered your questions 🙂
