### ISSUE TITLE
[FEATURE] Add option to deprecate block markup and attributes

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#291]
https://developer.wordpress.org/block-editor/developers/block-api/block-deprecation/

We will make it like transforms.js only for deprication

**Comment by dingo-d** [comment]
This is useful if things change on existing blocks, right?

**Comment by iruzevic** [comment]
Yes you can say ok i have removed this block attribute and created a new one so you can map them. Once you open a page in editor this block is converted automatically
