### ISSUE TITLE
BemMenu

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#323]
Can I use bem menu  for a example: "post categories" use to generate menu ?

**Comment by dingo-d** [comment]
Can you be a bit more specific? It's really not clear what you are trying to accomplish.

**Comment by marijang** [comment]
i7m trying to create menu list from post categories

**Comment by dingo-d** [comment]
Well, the BEM menu will just add specific classes (the updated version is here: https://github.com/infinum/eightshift-frontend-libs/pull/292 and https://github.com/infinum/eightshift-libs/pull/143) to the WP rendered out the menu. And WordPress already gives you the ability to add categories to your menu, so it should be working just fine

![Screenshot 2021-04-23 at 07 52 29](https://user-images.githubusercontent.com/8638515/115824897-f9a58500-a408-11eb-8c56-8d8c90714bbc.png)

**Comment by iruzevic** [comment]
There is no action here s I will close
