### ISSUE TITLE
[FEATURE] Remove Swiper from the libs

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#325]
Remove Swiper from the libs and add msg when using component/block that uses this package.

**Comment by marijang** [comment]
Why you removing swiper?

**Comment by dingo-d** [comment]
We are trying to make the dependency list as small as possible plus not tight coupling the blocks with concrete implementations. 

The idea is that with the carousel you'd be able to use whatever lib you want.

**Comment by iruzevic** [comment]
On installation using WP-CLI you will get the note how to install swiper on you project. But if you chose not to use it it is up to you.

This decision was made because Swiper dropped the IE11 support and on 2 projects we needed it so we had a really big problem of making it work.

And we don't want to be committed to a one lib.

**Comment by marijang** [comment]
That make sense.....
