### ISSUE TITLE
serverSideRender

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#327]
Hey,

when i using server side render there is lot's od problems with lists
always getting styles from default.

for example if you using ul in serverside render you will get ....

.editor-styles-wrapper ul, .editor-styles-wrapper ol {
    margin-bottom: 28px;
    padding-left: 1.3em;
    margin-left: 1.3em;
}

really anoying ....

**Comment by iruzevic** [comment]
does this happens  with the native blocks or our custom lists block?

Can you provide us with an code example?

**Comment by IvanGrginovInf** [comment]
@marijang if you're using a custom block you'd need to override those styles in `your-block-name-editor.scss`

**Comment by marijang** [comment]
![Uploading Screenshot 2021-04-29 at 13.47.11.png…]()

**Comment by iruzevic** [comment]
Sorry your link is broken

**Comment by marijang** [comment]
<img width="1053" alt="Screenshot 2021-04-29 at 13 47 11" src="https://user-images.githubusercontent.com/1381443/116549000-3f74b880-a8f5-11eb-9d73-75741641d394.png">

**Comment by marijang** [comment]
You see on the right .editor.styles

Because of that you put in featured-posts $serverSideRender['headingTag...... = 'div'

but you remove also that from paragraph and heading component....

**Comment by marijang** [comment]
add_filter('block_editor_settings', function ($editor_settings, $post) {
              unset($editor_settings['styles'][0]);

              return $editor_settings;
          }
);

maybe?

**Comment by dingo-d** [comment]
For every block and component, you should be able to override it with `your-block-name-editor.scss` as @IvanGrginovInf mentioned.

**Comment by marijang** [comment]
Yep that gonna be fun because i m using swiper for post slider......i m thinking to put message: "that you can view preview on site":D

So how you are dealing with databases.

For example 
i have one local database and test database (test) server
how you sync between test and dev.

because when user enter new content i want to get the content on my dev database ....

**Comment by dingo-d** [comment]
We use wpcli's search-replace. Get the DB dump from the staging and import it in your dev env, and then just run `wp search-replace staging.url dev.url`

**Comment by iruzevic** [comment]
There is no action here s I will close
