### ISSUE TITLE
Overriding webpack entry config problem

### ISSUE THREAD

**Issue by IvanGrginovInf** [infinum/eightshift-frontend-libs#33]
There seems to be an issue when you try to exclude certain files from being required (such as `application-blocks.js`)

This should be achieved by providing an override of `entry` in `wepack.config.js` like so:

```js
const projectSpecific = {
  entry: {
    applicationBlocks.js: false,
    applicationAdmin.js: false,
    applicationBlocksEditor.js: false,
  }
};
```

Doing this should skip the following files in the output.

**Comment by iruzevic** [comment]
this is fixed, added documentation
