### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#344]
How you load font from google?
Use in scss or ?

**Comment by dingo-d** [comment]
You can implement this handy little tool

https://github.com/WPTT/webfont-loader

Or you can enqueue them. IIRC the google will cache fonts.

You should avoid directly importing them using `@import` statements

**Comment by marijang** [comment]
get it through composer or put somewhere in src?

**Comment by dingo-d** [comment]
You mean the webfont loader thingy? You can require it using composer and then implement as instructed in the readme, probably through enqueuing.

**Comment by iruzevic** [comment]
There is no action here s I will close
