### ISSUE TITLE
[FEATURE] Add .env as a config entrypoint

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#357]
It would be cool if we had some kind of an entry point for all the variable config like other frameworks have. For instance URL for the browsersync etc. that we could modify locally, and then this wouldn't be committed to the lib, but could be modified based on whatever we want. 

This would prevent hardcoding development URLs and things like that.

- [ ] Find out is it possible and how to use .env in the JS and PHP part
- [ ] Modify setup script to accommodate these changes
- [ ] Implement and test

**Comment by iruzevic** [comment]
I will close this as we are not using this approach
