### ISSUE TITLE
[FEATURE] Implement Storybook Vite

### ISSUE THREAD

**Issue by volfkarlo** [infinum/eightshift-frontend-libs#387]
## Is your feature request related to a problem? Please describe.

Build of a storybook is a bit on the slower side. If there are few themes that require build it slows down the deployment process for a quite significant amount of time.

## Describe the solution you'd like

This ESBuilder should make a big improvement regarding storybook build(and React parts in general)
https://storybook.js.org/blog/storybook-for-vite/ 

## Additional context

This is definitely something that should get our attention. It lowers build time up to 100x.

**Comment by iruzevic** [comment]
we no longer add storybook to the projects out-of-the-box so it is only used for docs, no need to make this changes
