### ISSUE TITLE
[BUG] package.json and composer.json contain default lib data

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#398]
Another thing I noticed when you set up a project, the default `package.json` and `composer.json` that get copied over will contain all the data from the libs, i.e. the name will be prefixed with eightshift and the github URLs will also contain the eightshift repo url.

The problem with that is, if somebody uses the libs to publish something on npm/packagist, there could be some issues present.

We should either set up some minimum examples, or replace these things while copying the project using the script.

**Comment by iruzevic** [comment]
They cant publish anything to the npm or packagist because only we have write and publish rights. But we can update this why not

**Comment by dingo-d** [comment]
Yeah, this is more if they use our BP for their plugin that they wish to push to packagist or npm or something like this.

**Comment by iruzevic** [comment]
sure we can make this work, this needs to be updated in the https://github.com/infinum/eightshift-frontend-libs/tree/develop/setup/create-wp-project part

**Comment by iruzevic** [comment]
this is done in the latest release
