### ISSUE TITLE
[BUG] wp boilerplate use_block --name=accordion not pulling components, only blocks

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#408]
When using `wp boilerplate use_block --name=accordion` I only got the `accordion` block, but not any of the editor or option components, and they are referenced in the block.

So when you run `npm run start` the bundling throws errors.

**Comment by goranalkovic-infinum** [comment]
If you look in the documentation/readme for the block, it tells you to do
```
wp boilerplate use_block --name=accordion
wp boilerplate use_component --name=accordion
```
which solves the issue.

If you look at it like that, almost none of our blocks would actually work because they depend on components.

**Comment by dingo-d** [comment]
Yup, that makes sense. We should probably mention this in the docs when we use just components.
