### ISSUE TITLE
[BUG] Wrapper css vars are inherited in the child blocks when using CSS variables

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#417]
If I put a columns block and inside a column, any other block, when setting any of the variables in the wrapper on the columns, those variables will be inherited in the child wrappers.

So, for instance, setting a top margin on the columns wrapper to 100 will mean that any element inside will have the same top margin (unless the defaults are set to some other value than 0).

Setting any of these wrapper values to 0, won't actually set them to 0, which is also a bit annoying.

### EDIT

My guess is that in the `setVariablesToBreakpoints` method there is a check on line 612, where it checks for `!empty($attributeValue)`, which is a `false` in the case a `0` is provided, so this override isn't set.

The quick and dirty solution is to set all these margin values in the wrapper to `1`, so that they don't get overwritten. But this is just a bandage solution.

### EDIT 2

We need to also devise a way to exclude the colors if one is set on the parent. For instance, I can set the default to be a project color that is transparent, but if I set the parent to gradient, the child blocks will automatically have the gradient bg set on them.

**Comment by goranalkovic-infinum** [comment]
This does not happen anymore (checked in a clean project with FE Libs 8.2.1)
