### ISSUE TITLE
[FEATURE] Add ability to show the certain pickers in AdvancedColorPicker

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#418]
Currently, even if you don't want to use, for instance, gradient picker, but you do want to expose the gradients globally, there is no way to remove the gradient dropdown as a choice because of

```js
const showGradient = types.find(({ value }) => value === 'gradient') !== undefined;
```

Which will check the types set on line 82 of the `advanced-color-picker.js`. So it's always defined.

Additional control should be added in that component (`use*Type`) to toggle showing certain parts of that color picker.

**Comment by goranalkovic-infinum** [comment]
You can pass `types` you want to have available, for example:

```jsx
<AdvancedColorPicker
	types = [
		{
			label: __('No background', 'eightshift-frontend-libs'),
			value: ''
		},
		{
			label: __('Project color', 'eightshift-frontend-libs'),
			value: 'project'
		}
	]
/>
```

**Comment by dingo-d** [comment]
Indeed it works. Totally missed the fact I can just override that 🤦🏼‍♂️ Thanks!
