### ISSUE TITLE
[FEATURE] Check if duplicate component keys exist in project.

### ISSUE THREAD

**Issue by MetarDev** [infinum/eightshift-frontend-libs#429]
Currently you can have 2 components with the same name in `manifest.json` and no error will be thrown. If you have this you might experience weird behaviour where defaults won't be overriden in one, attributes won't save, etc.

We need some kind of check (ideally a global expection) that will trigger if you have 2 components with the same name.

**Comment by iruzevic** [comment]
this is done in the latest release
