### ISSUE TITLE
[FEATURE] Remove variation example key

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#447]
You can simple remove it but it looks like in 99% cases the example is the same as the variation attributes so we should make so if the example is not provided it uses the attributes but you should also be able to override it with example attributes if necessary.

This needs to be tested on variation storybook and block rendering and block preview in the editor.

**Comment by iobrado** [comment]
I tested this and I've discovered the following:
- if example attributes are removed from variation manifest, preview works in editor without any issues
- it doesn't work in storybook, looks like it requires example attributes. I even tried passing empty array of example attributes, didn't help
- even if all example attributes are copied to variation attributes, it still causes the error.

This a screenshot of error I'm getting in storybook:
![Screenshot 2021-11-05 at 12 58 15](https://user-images.githubusercontent.com/23059501/140507127-c9d32583-5c1c-488e-8019-59e78b317088.png)
