### ISSUE TITLE
[FEATURE] Implementation of Typography component

### ISSUE THREAD

**Issue by volfkarlo** [infinum/eightshift-frontend-libs#448]
As a result of the presentation of the Typography component to the team, we decided to introduce the Typography component to our Frontend libs.
 Font sizes will reflect some initial and most used font sizes.

Points of action
- adding typography component
- adding "How to" section to our docs
- correcting all the components to fit the typography component
- potentially add a mixin for better dev experience (`responsiveSize($fixedPart, $variablePart)` => `calc(var(--base-font-size, 0.625) * #{$fixedPart}rem) + #{$variablePart}vw`);

**Comment by iruzevic** [comment]
we are moving away from the typography component in the new way of working
