### ISSUE TITLE
On block setup in Boilerplate copy only specific blocks

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#45]
Currently we copy all components and all custom blocks on setup init script.
We need to limit it to:

**Components:**
- button
- heading
- image
- link
- lists
- paragraph
- tracking
- video
- google-rich-snippets

**Custom:**
- button
- heading
- image
- link
- lists
- paragraph
- video
- example

**Comment by IvanGrginovInf** [comment]
This will be done as part of https://github.com/infinum/eightshift-frontend-libs/pull/49.

**Comment by IvanGrginovInf** [comment]
This was done in #49, closing issue.
