### ISSUE TITLE
[FEATURE] Wrapper add ability to have multiple presets as buttons before options.

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#451]
This is for quick usage and presets

**Comment by goranalkovic-infinum** [comment]
@iruzevic would the users be able to make (one or more) presets themselves and load/save them (from the localStorage)? Or would this be defined through code and just surfaced to the users as one-click config buttons?

**Comment by iruzevic** [comment]
I tought about developer presetting them via the code and just set as a button but we all ready have this so this is ok I think?

**Comment by goranalkovic-infinum** [comment]
Will be added in FE libs 8.3.0 (with more expanded functionality!)
