### ISSUE TITLE
[FEATURE] Implement preset buttons for columns and grid block like on forms

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#476]
Something like this
<img width="1070" alt="Screenshot 2021-11-03 at 23 53 15" src="https://user-images.githubusercontent.com/23283324/140223131-05e29c59-4566-4471-89a1-0b3cb7ef2b70.png">

**Comment by goranalkovic-infinum** [comment]
Will be available in FE libs 8.3.0!

![image](https://user-images.githubusercontent.com/77000136/235132533-fd8e14c2-fd65-4471-ada8-ea2f15d8aa81.png)
