### ISSUE TITLE
[BUG] Sticky posts cause issues with Featured Posts block

### ISSUE THREAD

**Issue by iobrado** [infinum/eightshift-frontend-libs#492]
## Describe the bug

If there is one or more sticky posts, Featured Posts block displays them first in list, regardless if that post is selected or not.

Additionally, if we select only one post to display, it will display both that post and sticky post.

## Steps to Reproduce

1. Set one or more posts as sticky
2. Add Featured Posts block on any page

## How to fix it
Simply add `'ignore_sticky_posts' => true` to WP_Query

One important thing to note: This parameter doesn't completely exclude sticky posts from query, it simply ignores putting them first in the list, so the sticky posts will still be visible in the list, but they will be ordered regularly, like all other posts.

**Comment by iruzevic** [comment]
done
