### ISSUE TITLE
List change between ul and ol

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#499]
Is it possible to change between ol and ul

**Comment by mbmjertan** [comment]
Hi @marijang,

thank you for your question.

If you're talking about the `lists` component, you can pass an `listsOrdered` attribute to it containing `ul` or `ol`, which'll determine which element will be rendered in the DOM.

Here's the attribute registered in the `manifest.json` file: https://github.com/infinum/eightshift-frontend-libs/blob/develop/blocks/init/src/Blocks/components/lists/manifest.json#L19 and the component code: https://github.com/infinum/eightshift-frontend-libs/blob/develop/blocks/init/src/Blocks/components/lists/lists.php#L37

However, as far as I can see, there isn't an option to change that attribute in the editor, so you'll have to do one of the following, in order of preference:

* Add an option to change list type to `lists-options.js`
* Create a variation of the `lists` block for ordered lists which sets the `listsOrdered` attribute to `ol` (see the `variations` folder to see how you can do that)
* Pass `listsOrdered` to `Components::render` (which you can only do in certain cases, e. g. when the list is in a block)

We'll have this issue in mind for the future, though, and will fix it in frontend-libs as well. PRs are always welcome, though :)

**Comment by mbmjertan** [comment]
Hey @marijang,
this should be fixed on the `develop` branch now.
