### ISSUE TITLE
options.overrides returns object, so isUsed doesn't work (at least for browserSync)

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#50]
When I add 

```js
    overrides: {
      browserSyncPlugin: false,
    },
```

In my project, the resulting `isUsed` in the lib is always true. 

This should be fixed. Not sure if this is for all these overrides or just for browsersync 🤷‍♂

**Comment by iruzevic** [comment]
if you want to override the default config you should provide 'true' as a key value.

https://infinum.github.io/eightshift-frontend-libs/installation/register-webpack.html
