### ISSUE TITLE
Rellax or animation

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#515]
Hey i want to add animation or rellax.js

On some components for example card. But i want to be easy to add to all components. Also to use with php only. Not only through blocks.

What is best way to do it.

It will be nice to have something like wrapper functionality.

For example i want to add class and data props to card div not to create wrapper...around it

**Comment by mbmjertan** [comment]
Not sure I'm following you here. You're trying to add an additional class and data properties to a component?

You could add the class similarly to what we're doing here:

https://github.com/infinum/eightshift-frontend-libs/blob/develop/blocks/init/src/Blocks/components/card/card.php#L21-L25

As `Components::classnames` is a function that accepts an array of classname and generates a string you can use as the `class` attribute in HTML, you can programmatically add classes depending on attribute values, for instance something like this:
```php
$cardClass = Components::classnames([
	Components::selector($componentClass, $componentClass),
	Components::selector($blockClass, $blockClass, $selectorClass),
	Components::selector($additionalClass, $additionalClass),
        Components::selector($attributes['isAnimated'] ?? false, $blockClass, $selectorClass, 'animated'), // [1]
        $attributes['animation'] ? 'some-class-name' : '',  // [2]
]);
```
[1]: adds a BEM classname with the block `$blockClass`, selector `$selectorClass` and modifier `animated` if `$attributes['isAnimated'] ?? false` evaluates to `true`

[2]: adds a classname `some-class-name` if `$attributes['animation']` evaluates to `true`

You can similarly add data attributes to the HTML output conditionally, and you can do the same in the Block Editor as well ([look at card-editor.js](https://github.com/infinum/eightshift-frontend-libs/blob/develop/blocks/init/src/Blocks/components/card/components/card-editor.js#L24-L28) for an implementation example).

If you need this on all blocks, you might want to consider doing these modifications on [the wrapper itself](ttps://github.com/infinum/eightshift-frontend-libs/tree/develop/blocks/init/src/Blocks/wrapper): registering attributes you need in the wrapper manifest, adding editing options to `wrapper-editor.js` and modifying `wrapper.php` to output required classnames and data attributes, almost 1-to-1 as in the card example. 

Hope this helps. If I got something wrong understanding you, can you please further explain what you're trying to do?

Also, perhaps Discussions are a better place for questions. 🤷
