### ISSUE TITLE
getColortByName

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#517]
Here is there function which return color code / value from global manifest by given name

fore example getColor('primary')

**Comment by iruzevic** [comment]
Yep there is:

please check the documentation.

If you want to use the old ways using sass maps: https://infinum.github.io/eightshift-docs/docs/basics/global-settings
or modern way using css variables: https://infinum.github.io/eightshift-docs/docs/basics/blocks-styles/

**Comment by marijang** [comment]
hey i now that....

but i m using waypoint.js to detect when i enter section...(wrapper) now i need 
1. to get wrapper background color (extract from class)
2. get color code
3. set header background color from wrapper color..

that is the plan....so i put script into header....

**Comment by iruzevic** [comment]
This will be available in the next release
