### ISSUE TITLE
Refactor wrapper to use grid

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#542]
### Describe your feature request

Refactor wrapper to use grid as started in the https://github.com/infinum/eightshift-frontend-libs/tree/feature/wrapper branch

### Describe the solution you'd like

- [ ] restructure wrapper code
- [ ] remove unnecessary blocks
- [ ] refactor all blocks to use new wrapper layout

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by goranalkovic-infinum** [comment]
Wrapper has been using Grid since Frontend libs v8, we might revisit the "wrapperless wrapper" idea in the future, but we can close this one for now.
