### ISSUE TITLE
Wrapper hide

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#576]
Wrapper hide is not working if you set mobile hide

**Comment by mbmjertan** [comment]
Seems that media blender has, by default, an additional breakpoint smaller than `small`, and that we don't override it anywhere.

This is from their defaults:
```scss
$media-breakpoints: (
  small: 0 543,
  mobile: 544 767,
  tablet: 768 991,
  desktop: 992 1199,
  large: 1200
) !default;
```

@marijang - A workaround for this would be to override the breakpoints manually in `assets/styles/parts/_shared.scss`, e.g. like this:

```scss
@import 'media-blender';
$media-breakpoints: (
  mobile: 0 767,
  tablet: 768 991,
  desktop: 992 1199,
  large: 1200
);
```

**Comment by iruzevic** [comment]
Wrapper will be rewritten in the next release so I will close this issue
