### ISSUE TITLE
Eslint fails on eightshift-frontend-libs develop branch

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-frontend-libs#597]
### Describe your bug

Running `npm run lint` produces ESLint parsing errors:

```
  0:0  error  Parsing error: require() of ES Module /Users/mariobornamjertan/dev/eightshift-frontend-libs/node_modules/eslint-scope/lib/definition.js from /Users/mariobornamjertan/dev/eightshift-frontend-libs/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/mariobornamjertan/dev/eightshift-frontend-libs/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules
```

Gist with output of `npm run lint`: https://gist.github.com/mbmjertan/b3cbf60ba894ec32cf63290ea83cea7c

### Steps to Reproduce

1. `git clone git@github.com:infinum/eightshift-frontend-libs.git`
2. `npm install`
3. `npm run lint`

### Expected behavior

Successful eslint run

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
Fixed in the next release
