### ISSUE TITLE
Research and implement a more stable way to reference manifest schemas

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-frontend-libs#606]
We currently use this reference to the JSON schema for manifest files:

```"$schema": "https://raw.githubusercontent.com/infinum/eightshift-frontend-libs/develop/schemas/component.json",```

The issue with this is that we reference the `develop` branch, which might introduce issues when validating the schema when it's changed on the `develop` branch, as projects _might_ be using an older version. 

You might think for a second that this is a far-fetched concern 😄, but as manifest schemas have been radically different between major (and sometimes minor) releases of Frontend Libs, this seems like a very realistic developer experience bug.

An obvious way to do this is to use a release URL, but I have some implementation concerns about that.

- [ ] Research ways to reference manifest schemas so they're locked to a release
- [ ] Implement the new manifest schema reference

**Comment by mbmjertan** [comment]
The current version of the JSON Schema standard supports referencing schemas using **URLs**, meaning we can use local paths for schemas without worrying about directory separators on Windows, like so:

```json
{
    "$schema": "../schemas/config-schema.json",
    "title": "My app",
    "price": 7
}
```

@dingo-d checked this on a Windows machine and it works in both VSCode and PHPStorm. However, VSCode doesn't fully support the current version of the standard, so I'll have to check that this works on the older version as well.

If it does, I believe that it makes sense to reference the JSON schema from `node_modules`.

**Comment by dingo-d** [comment]
As mentioned in the other ticket: 

---

So there is this cool thing called [JSON Schema Store](https://www.schemastore.org/json/).

While browsing it I noticed that the block.json from GB is on the list.

So, maybe we could add our own schemas to the list?

### Describe the solution you'd like

See what is required on the [Contributing.md](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md) info, and submit a PR with our schemas?

We can then update the schema URL to

```json
  "$schema": "http://json-schema.org/draft-04/schema#",
```

Like `blocks.json` does in GB: https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/block.json

The only thing we need to test is how to handle versioning.

**Comment by iruzevic** [comment]
current setup works fine, I will close this
