### ISSUE TITLE
SCSS function for outputting media breakpoints defined in global manifest.json

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs#623]
### Describe your feature request

Create a SCSS function which takes `global-settings(breakpoints)` as a parameter from global manifest and outputs all needed breakpoints.

### Describe the solution you'd like

Can we have a SCSS function which takes these values and generates the media breakpoints?

These are the default boilerplate values for media queries defined in global [manifest.json](https://github.com/infinum/eightshift-frontend-libs/blob/b418748b17af70ec9b63ae81018255887338707a/blocks/init/src/Blocks/manifest.json#L24):
```json
"breakpoints": {
    "mobile": 480,
    "tablet": 960,
    "desktop": 1920,
    "large": 1921
}
```

This way the breakpoints would be defined in just one place, the global manifest.
Main reason for this is If a project requires adding new breakpoints there is no extra step in the setup.

### Environment info

Any

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by dingo-d** [comment]
Aren't the breakpoints exposed as CSS vars already? 🤔

**Comment by iruzevic** [comment]
noup because they need to be as a sass map for media-blender

**Comment by goranalkovic-infinum** [comment]
@dingo-d because you can't use CSS vars in media queries and we don't change their definitions, we wouldn't have too much use of breakpoints as CSS vars 😄 SASS map is the next best thing that we can use

**Comment by iruzevic** [comment]
merged
