### ISSUE TITLE
Copying blocks and components not working

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#636]
### Describe your bug

I've set up the test project using latest branches (develop), and I noticed that copying blocks/components is not working.

I've tried with accordion component

```bash
wp boilerplate blocks component --name='accordion'
Please check the docs for all available components.
You can find all available components on this link: https://infinum.github.io/eightshift-docs/storybook/.
Or here is the list of all available component names:

Error: The component '.../wp-content/themes/test-theme/node_modules/@eightshift/frontend-libs/blocks/init/src/Blocks/components/accordion' doesn\'t exist in our library.
```

The same happened for the group block and just the accordion block.

Also, the command name should be changed.

`wp boilerplate blocks component` and `wp boilerplate blocks block` is not a good name, as it's not clear what this command does without typing the `--help` parameter.

Since renaming the commands is a BC break, and will go in the new version, we should improve on this as well.

### Steps to Reproduce

1. Set up the project using `develop` branches
2. Try to add a block from the libs
3. See it fail

### Expected behavior

The command should work

### Environment info

- PHP version: 7.4.29
- Development environment: Laravel Valet
- Server type: Nginx
- Operating System and version: MacOS Monterey (12.4)
- Libs version: `develop`

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
this works now in the latest release
