### ISSUE TITLE
Update setup script

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#64]
There has been some changes on layout structure and we have to update setup script accordingly.

1. Setup script should be run using:

- npx create-wp-project (installs theme)
- npx create-wp-project --theme (installs theme)
- npx create-wp-project --plugin (installs plugin)

- npx create-wp-project --no-blocks (installs theme, removes blocks from the install)
- npx create-wp-project --theme --no-blocks (installs theme, removes blocks from the install)
- npx create-wp-project --plugin --no-blocks (installs plugin, removes blocks from the install )

2. Always copy [assets folder](https://github.com/infinum/eightshift-frontend-libs/tree/develop/blocks/init/assets) to the root of your project

3. If using blocks copy [blocks folder](https://github.com/infinum/eightshift-frontend-libs/tree/develop/blocks/init/blocks) to `src/blocks` folder.

4. If **not** using block. Don't copy blocks folder and go to `src/class-main.php` file and remove lines:

- use Eightshift_Libs\Blocks as Lib_Blocks;
- Lib_Enqueue\Enqueue_Blocks::class => [ Config::class, Lib_Manifest\Manifest::class ],
- Lib_Blocks\Blocks::class => [ Config::class ],

**Comment by IvanGrginovInf** [comment]
We probably need to make this line somehow optional:

```php
add_filter( 'allowed_block_types', [ $this, 'get_all_blocks_list' ] );
```

I.e. we need an option for "Use our blocks but don't disable default ones".

I'd even make this the default behavior but then provide some flag in order to make it like it is now (allow only eighshift's blocks).

@iruzevic @dingo-d thoughts?

**Comment by iruzevic** [comment]
> We probably need to make this line somehow optional:
> 
> ```
> add_filter( 'allowed_block_types', [ $this, 'get_all_blocks_list' ] );
> ```
> 
> I.e. we need an option for "Use our blocks but don't disable default ones".
> 
> I'd even make this the default behavior but then provide some flag in order to make it like it is now (allow only eighshift's blocks).
> 
> @iruzevic @dingo-d thoughts?

Definitely this should be next in line to fix

**Comment by IvanGrginovInf** [comment]
I agree but I was specifically talking about this part, thoughts?

> I'd even make this the default behavior but then provide some flag in order to make it like it is now (allow only eighshift's blocks).

**Comment by iruzevic** [comment]
Sure sounds good I will check how to make this happend

**Comment by dingo-d** [comment]
Add some defined constant and load if it's false? Not 100% sure how and where this is used 😬

**Comment by IvanGrginovInf** [comment]
> Add some defined constant and load if it's false? Not 100% sure how and where this is used 😬

That's just implementation, what I mean was are you ok with that being the default behavior when boilerplate is installed? I'll just ask you in person once we get to that part. 😄

**Comment by iruzevic** [comment]
this is done
