### ISSUE TITLE
Swiper

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#641]
Swiper causing that compile is not possible

@import '~swiper/swiper.scss';
@import '~swiper/modules/pagination/pagination.scss';

not working

error is:

Generated code for /Applications/MAMP/htdocs/bjn/wp-content/themes/b4b/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!/Applications/MAMP/htdocs/bjn/wp-content/themes/b4b/node_modules/postcss-loader/dist/cjs.js!/Applications/MAMP/htdocs/bjn/wp-content/themes/b4b/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!/Applications/MAMP/htdocs/bjn/wp-content/themes/b4b/node_modules/import-glob-loader/index.js!/Applications/MAMP/htdocs/bjn/wp-content/themes/b4b/src/Blocks/assets/styles/application-blocks-frontend.scss
1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Can't find stylesheet to import.\n  ╷\n2 │ @import '~swiper/modules/pagination/pagination.scss';\n  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  ╵\n  src/Blocks/custom/carousel/carousel-frontend.scss 2:9           @import\n  src/Blocks/assets/styles/application-blocks-frontend.scss 24:9  root stylesheet");
 @ ./src/Blocks/assets/application-blocks-frontend.js 8:0-51

**Comment by iruzevic** [comment]
please read the swiper package.json file. they have exported the css files and this is why this is not working.

use this import `@import '~swiper/css';`

**Comment by iruzevic** [comment]
as this is not an issue on boilerplate this will be closed
