### ISSUE TITLE
Update rc-slider package to v10

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#643]
### Describe your bug

When updating rc-slider to v10 i have found some errors.

### Steps to Reproduce

Please update and fix

### Expected behavior

To work

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by goranalkovic-infinum** [comment]
Updated in Libs v8
