### ISSUE TITLE
Editable header/footer

### ISSUE THREAD

**Issue by SenselessTaste** [infinum/eightshift-frontend-libs#644]
### Describe your feature request

It would be nice to have a feature like editable header and footer using blocks without editing code directly. 

### Describe the solution you'd like

Adding blocks in wordpress customizer

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by dingo-d** [comment]
Hi @SenselessTaste!

You can do this by using either FSE features (we avoid using them, they are still changing so it's not that 'safe' to use them) or with reusable blocks. 

By using [reusable blocks](https://infinum.github.io/eightshift-docs/docs/basics/blocks-reusable/#use-the-reusable-block-as-a-partial) you can create a 'partial' in the admin, then in theme options create an option where you'll select that certain reusable partial that can be used as a footer/header inside the correct template (`footer.php` or `header.php`).

**Comment by goranalkovic-infinum** [comment]
Hi @SenselessTaste,

as Denis mentioned, you can implement a "partials" system with Reusable blocks, and now in FE libs 8.3.0 there's a base navbar and footer block you can use.
