### ISSUE TITLE
CustomSelect re-render issue for deeply nested objects

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs#646]
### Describe your bug

Using a `<CustomSelect />` component with `loadOptions` attribute and `getFetchWpApi` doesn't re-render the component on state change.

### Steps to Reproduce

1. Create an deeply nested attribute in manifest.json for the block where the `<CustomSelect />` would be used.
E.g. :
```json
"featuredPostsQuery": {
	"type": "object",
	"default": {
		"postType": "post",
		"taxonomy": "",
		"terms": [],
		"posts": []
	},
	"items": {
		"type": "object"
	}
},
```
2. Fetch attributes in the `{block}-options.js` and have any component change state of any deeply nested `featuredPostsQuery` property (e.g. `featuredPostsQuery.postType`)  which should trigger a re-render of  `<CustomSelect loadOptions={getFetchWpApi()} />`

### Expected behavior

Expected behavior would be a re-render of the `<CustomSelect />` component but it seems to fall behind in sync one step.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/22823970/179008892-7d6e493e-9831-4d15-8e3d-af6fdac1a7c5.mov

### Environment info

Applicable to any OS, PHP, server & browser
- Libs versions: `>=6.1.0` 

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
we are no longer using the objects for handing attributes so it looks like there is no need to spend time on this issue
