### ISSUE TITLE
Implement a carousel ourselves?

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-frontend-libs#650]
### Describe your feature request

Swiper seems to have breaking changes _quite often_, and generally isn't very accessible. Their a11y plugin does resolve some major issues, though it isn't perfect.

I believe we could have much better performance, accessibility and provide a generally nicer experience if we were to implement a carousel ourselves, especially if we use CSS grid snapping. This would also allow us to snap the carousel's elements to a project's grid, which is currently a pain point when using Swiper.

For some inspiration, take a look at https://css-tricks.com/css-only-carousel/ and https://css-tricks.com/practical-css-scroll-snapping/

### Describe the solution you'd like

That's what I'd like to hear from you. What features do you expect from a carousel?

My "must haves" are:

- [ ] previous / next buttons
- [ ] trackpad scrolling support
- [ ] pagination buttons
- [ ] grid snapping

Feel free to add anything you'd like to see here so I can come up with an informed estimated of how long this could take.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
This is out of scope so we will not make this, Swiper is ok for major usage
