### ISSUE TITLE
Use schema store to serve the schema?

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#652]
### Describe your feature request

So there is this cool thing called [JSON Schema Store](https://www.schemastore.org/json/).

While browsing it I noticed that the block.json from GB is on the list.

So, maybe we could add our own schemas to the list?

### Describe the solution you'd like

See what is required on the [Contributing.md](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md) info, and submit a PR with our schemas?

We can then update the schema URL to

```json
  "$schema": "http://json-schema.org/draft-04/schema#",
```

Like `blocks.json` does in GB: https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/block.json

The only thing we need to test is how to handle versioning.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
this is a duplicate ticekt so I will close it

**Comment by dingo-d** [comment]
Duplicate: #606
