### ISSUE TITLE
Gdpr

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#656]
Hey, i see that you have gdpr analytics?
"wp boileprplate create analytics_gdpr_settings"

Is there component or block for view

**Comment by mbmjertan** [comment]
No, it only prepares an ACF-powered admin view for GDPR settings, registering fields and an editor for them. You can use those ACF fields to then prepare a frontend view yourself, and the service class provides helpers for retrieving that data or falling back to defaults.

In other words, it gives you an editor, ACF fields, and methods you can use to build components like this:
<img width="703" alt="Screenshot 2022-08-09 at 16 36 53" src="https://user-images.githubusercontent.com/1742806/183677599-8a55f08b-826c-4021-8911-7db662e4c25a.png">

However, you need to implement the actual component and GDPR compliance logic yourself, depending on your use case and requirements.

See this PR for more info on what the command does and a screen recording: https://github.com/infinum/eightshift-libs/pull/252
