### ISSUE TITLE
Sassdoc & Storybook not working

### ISSUE THREAD

**Issue by IvanGrginovInf** [infinum/eightshift-frontend-libs#66]
Seems both Sassdoc & Storybook aren't working (I get 404):

- https://infinum.github.io/documentation/sassdocs.html
- https://infinum.github.io/documentation/storybook.html

@iruzevic any idea why?

**Comment by iruzevic** [comment]
You are operating the wrong urls
https://infinum.github.io/eightshift-frontend-libs/storybook/

https://infinum.github.io/eightshift-frontend-libs/documentation/storybook.html


Where did you get these urls?

**Comment by IvanGrginovInf** [comment]
Ahh, ok thank you, not sure how I found them before because...

> Where did you get these urls?
https://infinum.github.io/eightshift-frontend-libs - in the sidebar, I'd swear those links were correct before.

**Comment by IvanGrginovInf** [comment]
Well this is a stupid bug (and it's not anything urgent, it can wait until monday). But here's how I (apparently) got these urls:

1. Open https://infinum.github.io/eightshift-frontend-libs
2. Check links in sidebar -> they should be ok
3. Click the `For the full documentation please check this link.` link (which should just refresh the page)
4. Check links in sidebar -> they're broken

The only difference seems to be that first time there's a trailing slash `/` in the url, and the next time (when links are broken) there isn't one. 🤷‍♂

**Comment by iruzevic** [comment]
this is fixed in PR #69
