### ISSUE TITLE
Storybook is not working

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#660]
### Describe your bug

When adding storybook package, and running `npm run storybook` there are tons of these kinds of messages

```bash
ModuleNotFoundError: Module not found: Error: Can't resolve '@wordpress/components' in '/Users/deniszoljom/Sites/infinum-academy/wp-content/themes/wordpress-academy-course/node_modules/@eightshift/frontend-libs/scripts/components/advanced-color-picker'
```

### Steps to Reproduce

1. Install a fresh project
2. Setup theme
3. Install `@eightshift/storybook` package
4. try to run `npm start storybook`

### Expected behavior

Storybook should load and showcase the blocks/components in the project

### Environment info

PHP: PHP 7.4.30
Dev env: Laravel Valet
Server type: Nginx
OS: MacOS Monterey 12.5.1
Libs version: 7

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
storybook is removed
