### ISSUE TITLE
v8 accordionItemTriggerContent not defined in accordion item manifest

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#676]
### Describe your bug

I tried to import all the blocks from the new 8 release branch and got the 

```bash
[02-Nov-2022 09:32:55 UTC] PHP Fatal error:  Uncaught Exception: accordionItemTriggerContent key does not exist in the accordion-item block manifest. Please check your implementation. in /boilerplate-8-version/vendor/infinum/eightshift-libs/src/Helpers/AttributesTrait.php:48
```

error

### Steps to Reproduce

1. Install the project from the release/8 branch: `npx create-wp-project --eightshiftFrontendLibsBranch="release/8.0.0"`
2. Add all the blocks and components
3. Try to add accordion and save the page

### Expected behavior

No errors

### Environment info

PHP 7.4
Mac OS 12.6 Monterrey
Node 16

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by goranalkovic-infinum** [comment]
Fixed in the meantime
