### ISSUE TITLE
PHP Component storybook rendering

### ISSUE THREAD

**Issue by IvanGrginovInf** [infinum/eightshift-frontend-libs#68]
We need to look into how we can render PHP part of the component's template in JS. This could be used for:

- Rendering PHP-only components (such as header) in Storybook
- Running Regression tests on both both JS & PHP parts of components

It should be possible in theory using https://www.npmjs.com/package/node-php-server but I need to test this out once we get storybook running locally.

**Comment by dingo-d** [comment]
We also need to keep track of GB progress, because the plan is to have html templates instead of php in the future https://github.com/WordPress/theme-experiments

**Comment by IvanGrginovInf** [comment]
> We also need to keep track of GB progress, because the plan is to have html templates instead of php in the future https://github.com/WordPress/theme-experiments

You still need something to render that html. Currently (unfortunately) it's PHP. Once they implement a (JS-based I'd assume) alternative, I'd be more than happy to review our approach to building components / blocks.

**Comment by IvanGrginovInf** [comment]
Also I've got PHP to render, now it's a matter of building assets. I'll probably wait until storybook is usable locally (I assume #70 will fix this) and try there.
