### ISSUE TITLE
Responsive, non-top-level attributes used with WidthOffsetRangeSlider shouldn't have a set default

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-frontend-libs#680]
### Describe your bug

Responsive, non-top-level attributes used with WidthOffsetRangeSlider shouldn't have a set default in the applicable block, component or wrapper manifest, as the WORS-provided Inherit button sets the value of an attribute to `undefined`, which therefore resets to the default. It is impossible to achieve inheritance with a set default in this case.

### Steps to Reproduce

1. Set e.g. `wrapperWidthMobile` default
2. Try to inherit from a previous breakpoint using `WidthOffsetRangeSlider`
3. It will reset to default

### Expected behavior

1. Set e.g. `wrapperWidthMobile` default
2. Try to inherit from a previous breakpoint using `WidthOffsetRangeSlider`
3. It wil inherit from the previous breakpoint properly

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

No

**Comment by goranalkovic-infinum** [comment]
All of the responsive components have configurable "inherit" value and the ability to change the function that determines if something is "inherited", so this is not an issue anymore.

Also, some of the defaults have been tweaked (e.g. in Wrapper and Columns)
