### ISSUE TITLE
How to enable comments?

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#691]
I m using woocommerce but i can't find out way reviews / comments are not working with your theme...

Did you disable comments?

**Comment by mbmjertan** [comment]
We did not disable comments, we just do not provide an implementation for comments in Frontend Libs.

The way you implement comments in _your_ theme is up to you. The Theme Developers Handbook goes into great detail about [a potential implementation of comment support in themes](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/). For a simple solution, I would suggest that you add the base logic for rendering comments into your `post.php` template (create it from the `page.php` template if you don't have it), and use components to render individual comment section elements.

**Comment by iruzevic** [comment]
answer was provided
