### ISSUE TITLE
package.json not updated correctly

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#697]
### Describe your bug

There are some entries in the `package.json` file that should be updated when you bootstrap the project.

The `description` field could be filled with the description from the setup script, the repo URLs will contain infinum's slugs in the git repos.

Small things like that.

I think the same should be fixed in `composer.json` and in the description of the `phpcs.xml.dist`, but those are minor issues.

### Steps to Reproduce

1. Setup theme using `npx` command
2. Check the descriptions and `packgage.json` file
3. ???
4. Don't profit, but see the wrong things inside of the file

### Expected behavior

Correct links, description should be set inside the files...

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
this is done in the latest release
