### ISSUE TITLE
AsyncMultiSelect caching issue

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs#703]
### Describe your bug

`noOptionCaching` does not seem to be working, local storage is being read from despite the flag.

### Steps to Reproduce

Change the component `loadOptions` input

### Expected behavior

LocalStorage should be ignored when using the `noOptionCaching` flag.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by goranalkovic-infinum** [comment]
Ah, I see the confusion here :)

`noOptionCaching` in the `AsyncMultiSelect` controls the react-select's internal option caching, and doesn't affect `getFetchWpApi`.

If you want to skip cache in `getFetchWpApi`, pass `noCache: true` to its options.
