### ISSUE TITLE
Columns - Spacing and Layout

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#704]
When i add columns block and in options when i select "spacing & layout" then i can't see columns width slider....not showing

**Comment by marijang** [comment]
Yes

**Comment by marijang** [comment]
8.1.0

**Comment by marijang** [comment]
<img width="303" alt="Screen Shot 2023-03-23 at 14 20 57" src="https://user-images.githubusercontent.com/1381443/227217006-72558d3f-1c79-4847-b379-1033257700ee.png">

**Comment by goranalkovic-infinum** [comment]
Hi Marijan,
thank you for the bug report!

The "Spacing and layout" option shouldn't be there, as Columns aren't meant to have their width&offset changed because they provide such functionality to their inner blocks.

Please add this to your Columns block manifest, under attributes:
```
"wrapperUseShowControl":  {
	"type": "boolean",
	"default": false
},
"wrapperSimpleShowControl":  {
	"type": "boolean",
	"default": true
},
```

It'll be fixed in the next Frontend Libs release.

**Comment by marijang** [comment]
Ok then why always is 14 columns grid?

**Comment by goranalkovic-infinum** [comment]
The first and the last column are the "gutters" (the areas between your content and the edge of the browser).

So, if you want an image to be edge-to-edge, for example, you would stretch it across all 14 columns.

**Comment by marijang** [comment]
yes but is not same if i say this scenario:
1. Group Block inside is heading: offset 1
2. Columns -> Column: offset 1

Elements is not on same position

**Comment by goranalkovic-infinum** [comment]
That is the desired behavior - by default, all wrappers are 12-column (they do not include gutters).
If you enable "Full-width" on the wrapper, then the behavior is the same (the first and the last columns are gutters)

**Comment by marijang** [comment]
If you put column gap 0 then you will never get same position

**Comment by marijang** [comment]
for example 3 columns a want same offset like block before heading (offset one column start and the end)
How to create that?
<img width="229" alt="Screen Shot 2023-04-17 at 16 28 39" src="https://user-images.githubusercontent.com/1381443/232517050-03cc77f0-c1fb-43b6-9a7e-99019be53f39.png">

**Comment by marijang** [comment]
First is heading: offset 1
Second is columns width 4 offset 1 if i put offset 2 and gap 50 then it will be ok but i have 3 columns .... then 
offset 2 3x width 4 and offset 2 is more then 14

**Comment by goranalkovic-infinum** [comment]
The "Spacing and layout" option will not show in new themes created with Frontend libs v8.2.1 or newer.

For the configuration question please open a thread under "Discussions".
