### ISSUE TITLE
Media placeholder missing in the Editor

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-frontend-libs#710]
### Describe your bug

The media placeholder is not rendering in the editor
Libs v8

### Steps to Reproduce

Add Image block in the editor

### Expected behavior

"To work" - quote by Bica

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by simun-ivanac** [comment]
If I may jump in, just changing this 2 lines of code should be sufficient

this is for empty placeholder: `{_.isEmpty(imageUrl['large'])`
this is for image rendering: `{!_.isEmpty(imageUrl['large'])`

Someone please correct me in case you have better solution :)

**Comment by piqusy** [comment]
Yup, that seems to be the fix. Nice catch @simun-ivanac

**Comment by goranalkovic-infinum** [comment]
Fixed in Frontend libs 8.2!
