### ISSUE TITLE
rc-util error in custom slider component

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#711]
### Describe your bug

After updating to 8.1.0 version I keep getting the following error:

```
ERROR in ./node_modules/@eightshift/frontend-libs/scripts/components/custom-slider/tooltip-handle.js 4:0-34
Module not found: Error: Can't resolve 'rc-util/lib/raf' in '/wp-content/themes/theme/node_modules/@eightshift/frontend-libs/scripts/components/custom-slider'
 @ ./node_modules/@eightshift/frontend-libs/scripts/components/custom-slider/column-config-slider.js 4:0-66 135:18-48
 @ ./node_modules/@eightshift/frontend-libs/scripts/index.js 15:0-85 15:0-85
 @ ./src/Blocks/custom/carousel/carousel-block.js 3:0-81 17:4-32
 @ ./src/Blocks/custom/ sync -block.js$ ./carousel/carousel-block.js
 @ ./src/Blocks/assets/scripts/application-blocks-editor.js 21:179-232
 @ ./src/Blocks/assets/application-blocks-editor.js 12:0-45

...

Error: Can't resolve '~rc-slider/assets/index.css' 
```

### Steps to Reproduce

1. Install latest lib
2. Add block using custom slider component
3. Get the above errorthe 

### Expected behavior

No error

### Environment info

- PHP 7.4 and 8.0
- Valet
- Nginx
- MacOS Ventura 13.3
- Libs 8.1.0

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by goranalkovic-infinum** [comment]
@dingo-d I've checked this with FE libs 8.2, all seems to be fine.

Could you please try it with that, and if it still doesn't work, please provide the `-options.js` file.

**Comment by dingo-d** [comment]
I've solved it in a way that I've added it as a dependency on the project. I'll try to update the libs to 8.2 and see if this happens again 👍🏼

**Comment by goranalkovic-infinum** [comment]
@dingo-d can you please confirm if you can still reproduce it?

**Comment by dingo-d** [comment]
Nope, still happens when I updated to 8.3.0, but I think that maybe this is due to the project 🤷🏼‍♂️
