### ISSUE TITLE
Number picker component is off

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#712]
### Describe your bug

I think this is somehow related to WP 6.2 that was released because this looked ok on the older versions.

The input in the custom input field is shifted up relative to the up and down arrow buttons.

There was some class that added bottom margin.

### Steps to Reproduce

1. Install libs on wp 6.2
2. Check out any spacing option

### Expected behavior

The component should look like this

<img width="360" alt="image" src="https://user-images.githubusercontent.com/8638515/231876530-12d83c2c-66d6-4143-ac44-091beacd6457.png">

### Screenshots, screen recording, code snippet

<img width="330" alt="image" src="https://user-images.githubusercontent.com/8638515/231876044-da91b0a5-93d4-4f09-aac3-32d68fbfb571.png">

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by goranalkovic-infinum** [comment]
Fixed in Frontend libs 8.2!
