### ISSUE TITLE
LayoutMore

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#716]
Layout more should have responsive options.
Because I need to make responsive layout. When i preview i want 2 columns on dekstop i want 3

**Comment by goranalkovic-infinum** [comment]
Hi Marijan,
the libs are meant to be as generic as possible, so they can be shaped into anything a specific project will need.

However, it's really simple to add a new layout to the _Layout_ component:

**Add your layout to the manifest**
Add an entry to the `"options"` -> `"layoutType"`, something like:
```json
{
	"label": "Custom",
	"value": "custom",
	"icon": "star"
}
```
Add an entry to the `"combinations"` -> `"layoutType"`, something like:
```json
"custom": {
	"layoutTotalItems": 4
}
```
**Add the accompanying style**
In the `layout-style.scss` file add:
```css
.layout {
	...

	&[data-layout-type='custom'] {
		#{$this}__wrap {
			// Add your styles here
		}
	}
}
```
and that should be it!

**Comment by marijang** [comment]
I know how to change to my specific component but it will be great to have have responsive options here

**Comment by goranalkovic-infinum** [comment]
Thanks for the suggestion, but we're not planning to implement this currently.
