### ISSUE TITLE
Selecting Gradient background crashes the block

### ISSUE THREAD

**Issue by iobrado** [infinum/eightshift-frontend-libs#721]
### Describe your bug

When using any block with a wrapper on ES Frontend Libs 8.2.1, trying to add a gradient background will crash the block and show the "This block has encountered an error and cannot be previewed." message. The `Project Color` and `None` options work fine.

The error in the console is:
`TypeError: Cannot read properties of undefined (reading 'length')`

### Steps to Reproduce

1. Install ES Frontend Libs 8.2.1
2. Add any block
3. Go to Spacing & Layout -> Background
4. Select Gradient

### Expected behavior

To work.

I'm sorry, I had to 😂 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/23059501/235154547-e7031be7-bb3d-40f3-8135-bbcab5b4ce5c.mov

### Environment info

- PHP 7.4
- WP 6.2
- ES Frontend Libs 8.2.1
- Laravel Valet
- tested with Node 16 and Node 18, the result is the same

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by goranalkovic-infinum** [comment]
Will be fixed in FE Lib 8.3.0!

**Comment by goranalkovic-infinum** [comment]
Fixed!
