### ISSUE TITLE
Repeater in options crashes block

### ISSUE THREAD

**Issue by simun-ivanac** [infinum/eightshift-frontend-libs#726]
### Describe your bug

Using `Repeater` and `RepeaterItem` crashes the block.

### Steps to Reproduce

Add `Repeater`
Add `RepeaterItem`
Add some option inside `RepeaterItem`

### Expected behavior

Just to work.

### Screenshots, screen recording, code snippet
<img width="746" alt="image" src="https://github.com/infinum/eightshift-frontend-libs/assets/19992824/16dde94e-862b-4a1f-95ad-72b4a41a9465">

![image](https://github.com/infinum/eightshift-frontend-libs/assets/19992824/cb4abf15-cad4-4619-b623-9c08f4ff9b80)

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by goranalkovic-infinum** [comment]
Note to self: this is the fix
![image](https://github.com/infinum/eightshift-frontend-libs/assets/77000136/1c1eec58-cea9-46c8-81cf-8e3205bbf72d)

(if there's only a single child item)
