### ISSUE TITLE
WidthOffsetRangeSlider

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#729]
`<WidthOffsetRangeSlider
	{...generateWidthOffsetRangeSliderConfig({
		isFullWidthAttributeName: 'jambotronIsFullWidth',
		offsetAttributeName: 'jambotronContentOffset',
		widthAttributeName: 'jambotronContentWidth',
		manifest: manifest,
		attributes: attributes,
		setAttributes: setAttributes,
		minMaxStepOptionName: 'widths',
		showFullWidth: showJambotronIsFullWidth,
		numericValues: true,
	})}
/>`

Why is not working when i put that code into component jumbotron not block.

Simply not storing values or i can slide. I put everything into manifest

for example
`
"jumbotronColumnWidthLarge": {
  "type": "integer",
  "default": 8
},
"jumbotronColumnWidthDesktop": {
  "type": "integer"
},
"jumbotronColumnWidthTablet": {
  "type": "integer"
},
"jumbotronColumnWidthMobile": {
  "type": "integer",
  "default": 14
},

"responsiveAttributes": {
        "jumbotronColumnWidth": {
	        "large": "jumbotronColumnWidthLarge",
	        "desktop": "jumbotronColumnWidthDesktop",
	        "tablet": "jumbotronColumnWidthTablet",
	        "mobile": "jumbotronColumnWidthMobile"
        },
        "jumbotronColumnOffset": {
	        "large": "jumbotronColumnOffsetLarge",
	        "desktop": "jumbotronColumnOffsetDesktop",
	        "tablet": "jumbotronColumnOffsetTablet",
	        "mobile": "jumbotronColumnOffsetMobile"
        }
},

`

**Comment by goranalkovic-infinum** [comment]
Hi Marijan,
can you please provide the entire manifest?

**Comment by marijang** [comment]
``
