### ISSUE TITLE
Make wrapper simpler to load as standalone component

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#738]
### Describe your feature request

We should be able to use the wrapper as a standalone component and make it simple. For example, if you want to use a wrapper in the archive template around your content.

### Describe the solution you'd like

1. Make the `render` method simpler to load the wrapper. If the template path outputs a `wrapper` it should work.
2. Make `wrapperManualContent` and `wrapperOnlyOutput` as standard attributes in wrapper and make necessary code changes. 
3. Write a tutorial how to do it.

### Environment info

https://codefile.io/f/qCvhnpYiCB

```php
if (have_posts()) {
	while (have_posts()) {
		the_post();

		echo Components::render(
			'wrapper.php',
			[
				'wrapperOnlyOutput' => true,
				'wrapperManualContent' => apply_filters('the_content', get_the_content()),
			],
			Components::getProjectPaths('blocksDestinationWrapper'),
			true
		);
	}
}
```

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by kancijan** [comment]
Real use case example: https://codefile.io/f/LScsAehHB4
![image](https://github.com/infinum/eightshift-frontend-libs/assets/135589039/939ea4d4-a376-4906-ac3d-3a269014c778)
