### ISSUE TITLE
[FEATURE] - Make installation available from other branches than the infinum repo

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#749]
Currently, the `eightshiftLibsRepo` is a hardcoded value, which makes installation of different forks for testing purposes, a bit harder (you need to manually change repos). Would it be possible to make this configurable as well? By default, the branch will be the infinum's repo, but by passing the correct repo info, it would be pulled from that repo instead.

https://github.com/infinum/eightshift-frontend-libs/blob/25e68168ed5c8247fd134ff0df762c757cd9e2d5/setup/create-wp-project/src/dependencies.js#L34-L36

**Comment by iruzevic** [comment]
sure I don't see why not tnx for the suggestion

**Comment by dingo-d** [comment]
The only extra thing that should be changed, for Composer that is, is the addition of the `repositories` key, but that shouldn't be too hard I think.

https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by iruzevic** [comment]
this is done in the latest release
