### ISSUE TITLE
[FEATURE] - Use copyright component in site-footer block

### ISSUE THREAD

**Issue by kancijan** [infinum/eightshift-frontend-libs#752]
We have the Copyright component, but it's not used in the [site-footer](https://github.com/infinum/eightshift-frontend-libs/tree/develop/blocks/init/src/Blocks/custom/site-footer) component.

**Comment by goranalkovic-infinum** [comment]
![image](https://github.com/infinum/eightshift-frontend-libs/assets/77000136/852ac1b1-00e3-4a78-8981-fb133f1ac461)
