### ISSUE TITLE
[BUG] - External packages returns errors

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#760]
When setting up new theme and instaling all blocks with dependencies in Webpack I get these errors

![Screenshot 2023-10-26 at 08 56 00](https://github.com/infinum/eightshift-frontend-libs/assets/23283324/5c397b24-0422-442f-b5aa-d699d7c78b6a)

**Comment by goranalkovic-infinum** [comment]
Fixed in Libs 9.1.0. Also, the prompts when adding the block now points to the version that was current at the time of publishing that Libs version.
