### ISSUE TITLE
[FEATURE] - New icons

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#768]
I need:

- [] star rating block icon
- [] "store entries to db" icon
- [] empty entries like this
- [] empty locations like this
![Screenshot 2023-11-27 at 09 51 33](https://github.com/infinum/eightshift-frontend-libs/assets/23283324/ffec4a08-51a5-4933-8be6-1d93332957af)

**Comment by goranalkovic-infinum** [comment]
Added in the meantime
