### ISSUE TITLE
[FEATURE] Adding `.nvmrc` to install script

### ISSUE THREAD

**Issue by gabriel-glo** [infinum/eightshift-frontend-libs#77]
This is just a suggestion for adding `.nvmrc` file. With this file we can change the node version for users that use nvm and perhaps have older version of node selected.

https://github.com/nvm-sh/nvm#nvmrc

Is this something that could be useful for us or our users? What do you think about this generally?

**Comment by IvanGrginovInf** [comment]
This is useful only for people who have `nvm` setup locally and I'd wager those people are not the ones with outdated `node` versions.

The setup was tested just fine down to LTS Carbon (8.17.0) so I don't think outdated node versions are not that much of an issue. IMO adding this would be useful if we required a specific node version.

But then again it doesn't hurt to add it, maybe it will be beneficial to someone. 🤷‍♂

**Comment by iruzevic** [comment]
duplicate  #361
