### ISSUE TITLE
[QUESTION] -  woocommerce store api

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#775]
Woocommerce has new store api. The store api i accessable via rest api.

Now want to preload web request and store it to registry so that the output is available to all my blocks?
What is the best way to do it?

i m using  "rest_preload_api_request" function. and i want to store on first call of endpoint to "block store" repo...

This is abstract block from their repo
https://github.com/woocommerce/woocommerce-blocks/blob/175138605f24c63729bd5a977d839597da5ca977/src/BlockTypes/AbstractBlock.php

**Comment by goranalkovic-infinum** [comment]
Hi Marijan,
this doesn't seem to be related to the Eightshift Development Kit.

Stores are by default a feature of Gutenberg itself, and WooCommerce is extending them for its use.

You might want to try the [WooCommerce GitHub repository](https://github.com/woocommerce/woocommerce-blocks).

Kind regards
