### ISSUE TITLE
[QUESTION] - Accessing InnerBlocks on PHP Block Render Function

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#784]
Can i access inner blocks into php part of component if i m using innerBlocks?

for example?

function render( $atts, $content, $block_class ) {

	// Check how many inner blocks are available
	$item_count = $block_class->inner_blocks->count();
}

**Comment by iruzevic** [comment]
InnerBlocks variable is only available in the blocks and not in the components. If you need it in the components you can pass the count at a prop(attribute) to the component
