### ISSUE TITLE
[QUESTION] - Colorpicker

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#787]
Is there option in color picker that i can enter custom color? not gradient

**Comment by iruzevic** [comment]
@goranalkovic-infinum any comments here?

**Comment by marijang** [comment]
Advanced color picker is awsome but it will be nice to enter custom color code:D

**Comment by goranalkovic-infinum** [comment]
The `AdvancedColorPicker` already allows entering custom hex codes for solid colors.

**Comment by marijang** [comment]
Danke
