### ISSUE TITLE
[FEATURE] - Warn the user if they run the npx create-wp-project command in the wrong folder

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#795]
It would be a good feature to have, when you don't look where you are in the terminal and you accidentally run the command in the plugin folder or somewhere like that, for the command to warn you with something like:

> It seems like you are not in the root of the project/themes folder (wherever you need to be). Are you sure you want to continue?

Or at least detect where you are and try to automatically navigate you to the correct folder so you don't run into weird things or failed setups. Like automatically `cd` you to correct directory if possible.

This totally didn't happen to me just moments ago 👀

**Comment by iruzevic** [comment]
this is done in the latest release
