### ISSUE TITLE
[FEATURE] - Skip adding storybook when adding blocks by default

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#813]
Just an idea, since the storybook is not used most of the time, it would be a good idea not to include the `docs` folder when we copy the blocks from the libs into the project.

Maybe have a flag, like `--include-storybook` if we need to include them.

**Comment by goranalkovic-infinum** [comment]
Storybook is not a part of Libs anymore (since v10), so I guess this isn't an issue anymore 😄

**Comment by dingo-d** [comment]
Yeah, but `docs` are a part of every component and block, either when you run the `init theme` or when you pull the component using wpcli 😉 

The `docs` folder creates unnecessary clutter in the project that isn't using the storybook.

**Comment by dingo-d** [comment]
Ok, scratch that, npx command isn't updated I guess so the last version I pulled wasn't the v10 of FE libs 👍🏼
