### ISSUE TITLE
Table of Contents not working due to a Class name change.

### ISSUE THREAD

**Issue by zero4281** [infinum/eightshift-frontend-libs#836]
Line number 16 of the index.js file broke when WordPress updated the class name from .main-content to .entry.content.  Updating this one line of javascript seems to fix the issue.

https://github.com/infinum/eightshift-frontend-libs/blob/298d66650c0e9375ddf0c0cb3446caf186494eab/blocks/init/src/Blocks/custom/table-of-contents/assets/index.js#L16

**Comment by goranalkovic-infinum** [comment]
Hi, thanks for the input!

However, in the default Eightshift setup the body class _is_ set to `main-content` and is not affected by WordPress updates.

Feel free to customize it in your theme if your setup is slightly different 🙂
