### ISSUE TITLE
Wrong URL for examples of colors, shared variables etc.

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#93]
There are links in the code that point to nonexistent pages on GitHub.

https://github.com/infinum/eightshift-frontend-libs/blob/658c59110918fb8269189f2d79613e2aed621c26/blocks/init/assets/styles/parts/utils/_colors.scss#L6

These should be removed

**Comment by iruzevic** [comment]
@dingo-d not sure but can you test this. When I open the links they are correct:

https://github.com/infinum/eightshift-frontend-libs/blob/develop/styles/scss/_core.scss
https://github.com/infinum/eightshift-frontend-libs/blob/develop/styles/scss/_colors.scss

**Comment by dingo-d** [comment]
Oh, my bad, must have copied from an older place in my project. I have these:

```
https://github.com/infinum/eightshift-frontend-libs/blob/develop/scss/_colors.scss
```

which are not working.
