### ISSUE TITLE
Plugin installation leaves the main file name eightshift-boilerplate.php

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#96]
## Current Behavior

It seems that when you run `npx create-wp-project plugin` the rename script is not changing the main entrypoint file, or contents of the docblock.

In my plugin I have eightshift-boilerplate.php with
```php
<?php
/**
 * Plugin Name: Eightshift Boilerplate Title
 * Plugin URI:
 * Description: Eightshift Boilerplate Description
 * Author: Team Eightshift
 * Author URI: https://eightshift.com/
 * Version: 1.0.0
 * Text Domain: this-is-correctly-changed
 *
 * @package This_Is_Correctly_Changed
 *
 * @since 1.0.0
 */
```
## Expected Behavior

The plugin related info should be changed with the script.

## Steps to Reproduce (for bugs)

1. `npx create-wp-project plugin`
2. Check the plugin main file to see if the name you've set is there

## Your Environment

* PHP version: 7.2.24
* Development environment: Valet+
* Server type: Nginx
* Operating System and version: MacOS 10.15.3

**Comment by IvanGrginovInf** [comment]
Thank you for moving the issue, it should be a simple fix.
